cd /D "%~dp0"
KENSSharp.exe -r e "0_15MN.bin"
KENSSharp.exe -r e "1_3MN.bin"
KENSSharp.exe -r e "1_4MN.bin"
KENSSharp.exe -r e "1_5MN.bin"
KENSSharp.exe -r e "1_12MN.bin"
KENSSharp.exe -r e "2_5MN.bin"
KENSSharp.exe -r e "2_12MN.bin"
KENSSharp.exe -r e "2_34MN.bin"
KENSSharp.exe -r e "3_12MN.bin"