cd /D "%~dp0"
KENSSharp.exe -r n "0_15MN.bin"
KENSSharp.exe -r n "1_12MN.bin"
KENSSharp.exe -r n "1_3MN.bin"
KENSSharp.exe -r n "1_4MN.bin"
KENSSharp.exe -r n "1_5MN.bin"
KENSSharp.exe -r n "2_12MN.bin"
KENSSharp.exe -r n "2_34MN.bin"
KENSSharp.exe -r n "2_5MN.bin"
KENSSharp.exe -r n "3_12MN.bin"
cls