@Echo Off
cls
REM Generates the Chaotix header for the PWM INI file for SMPSPlay
del PWM.ini

Echo Creating PWM.INI header for SMPSPlay...
ECHO(
ECHO(

ECHO ; Generated by Chaotix ROMulan PWM Handler >> PWM.ini
ECHO( >> PWM.ini
ECHO ; Stanard 32X PWM DAC driver rates >> PWM.ini
ECHO BaseRate = 11025 >> PWM.ini
ECHO RateDiv = 0.00 >> PWM.ini
ECHO( >> PWM.ini
ECHO ; 0 - normal >> PWM.ini
ECHO ; 1 - linear interpolation >> PWM.ini
ECHO ResampleMode = 0x01 >> PWM.ini
ECHO( >> PWM.ini
ECHO ; 0 - delay by xx cycles >> PWM.ini
ECHO ; 1 - add xx to tick value and process sample when overflowing >> PWM.ini
ECHO ;     (uses RateDiv as "overflow" value) >> PWM.ini
ECHO RateMode = 0x01 >> PWM.ini
ECHO RateOverflow = 0x0800 >> PWM.ini
ECHO( >> PWM.ini
ECHO DrumIDBase = 00 >> PWM.ini
ECHO( >> PWM.ini