cd /D "%~dp0"
KENSSharp.exe -r e "01MN.bin"
KENSSharp.exe -r e "2MN.bin"
KENSSharp.exe -r e "3MN.bin"
KENSSharp.exe -r e "4MN.bin"
KENSSharp.exe -r e "5D.bin"
KENSSharp.exe -r e "5M.bin"
KENSSharp.exe -r e "5N6M.bin"
KENSSharp.exe -r e "5S.bin"
KENSSharp.exe -r e "6DS.bin"