cd /D "%~dp0"
KENSSharp.exe -r n "0_15MN.bin"
KENSSharp.exe -r n "0_Boss.bin"
KENSSharp.exe -r n "1_3MN.bin"
KENSSharp.exe -r n "1_12MN.bin"
KENSSharp.exe -r n "1_45MN.bin"
KENSSharp.exe -r n "2_15MN.bin"
KENSSharp.exe -r n "3_3MD.bin"
KENSSharp.exe -r n "3_3SN.bin"
KENSSharp.exe -r n "3_12MD.bin"
KENSSharp.exe -r n "3_12SN.bin"
KENSSharp.exe -r n "3_45MD.bin"
KENSSharp.exe -r n "3_45SN.bin"