

;
; +-------------------------------------------------------------------------+
; |   This file	has been generated by The Interactive Disassembler (IDA)    |
; |	      Copyright	(c) 2011 Hex-Rays, <support@hex-rays.com>	    |
; |			 License info: 48-327F-7274-B7			    |
; |			       ESET spol. s r.o.			    |
; +-------------------------------------------------------------------------+
;
; Input	MD5   :	F3C774EED7A9A03CB3121E4CBDB1DFA9
; Input	CRC32 :	595D61BF

; ---------------------------------------------------------------------------
; File Name   :	D:\VStudio-Programme\ASM68k\chaotix_hg-e4c579069ff6\snddrv.bin
; Format      :	Binary file
; Base Address:	0000h Range: 0000h - 2000h Loaded length: 2000h

; Processor	  : z80	[]
; Target assembler: Zilog Macro	Assembler

; ===========================================================================

; Segment type:	Regular
		segment	RAM

loc_0:
		di
		di
		im	1
		jp	InitDriver
; ---------------------------------------------------------------------------
		align 8

; =============== S U B	R O U T	I N E =======================================


ReadPtrTable:				; CODE XREF: TrkUpdate_Proc+39p
					; TrkUpdate_Proc+55p ...
		ld	c, a
		ld	b, 0
		add	hl, bc
		add	hl, bc
		ld	a, (hl)
		inc	hl
		ld	h, (hl)
		ld	l, a
		ret
; End of function ReadPtrTable

; ---------------------------------------------------------------------------
		align 8

; =============== S U B	R O U T	I N E =======================================


WriteFMIorII:				; CODE XREF: SendFMFreq+Fp
					; SendFMFreq+13p ...

; FUNCTION CHUNK AT 002E SIZE 00000002 BYTES

		bit	2, (ix+0)
		ret	nz
		add	a, (ix+1)
		bit	2, (ix+1)
		jr	nz, WriteFMIIPart
; End of function WriteFMIorII


; =============== S U B	R O U T	I N E =======================================


WriteFMI:				; CODE XREF: SendFMFreq+37p
					; SendFMFreq+3Ep ...
		ld	(4000h), a
		ld	a, c
		ld	(4001h), a
		ret
; End of function WriteFMI

; ---------------------------------------------------------------------------
; START	OF FUNCTION CHUNK FOR WriteFMIorII

WriteFMIIPart:				; CODE XREF: WriteFMIorII+Cj
		sub	4
; END OF FUNCTION CHUNK	FOR WriteFMIorII

; =============== S U B	R O U T	I N E =======================================


WriteFMII:				; CODE XREF: DoPause+11Ep
		ld	(4002h), a
		ld	a, c
		ld	(4003h), a
		ret
; End of function WriteFMII

; ---------------------------------------------------------------------------

VInt:
		di
		call	loc_3C

loc_3C:					; DATA XREF: RAM:loc_40w
		ld	a, 0
		add	a, 80h

loc_40:
		ld	(loc_3C+1), a
		jr	nc, locret_4B
		call	DoSoundQueue
		call	UpdateAll

locret_4B:				; CODE XREF: RAM:0043j
		ret
; ---------------------------------------------------------------------------
		align 8
aOnByMilpo:	.ascii 'on by MILPO'
; ---------------------------------------------------------------------------

InitDriver:				; CODE XREF: RAM:0004j
		ld	sp, 2000h
		ld	c, 0

loc_60:					; CODE XREF: RAM:0065j
		ld	b, 0

loc_62:					; CODE XREF: RAM:loc_62j
		djnz	$		; wait a bit
		dec	c
		jr	nz, loc_60
		call	StopAllSound
		call	SendPSGState
		xor	a

loc_6E:
		ld	hl, PSGState_Ch1
		ld	b, 10h

loc_73:					; CODE XREF: RAM:0075j
		ld	(hl), a		; clear	PSG state
		inc	hl
		djnz	loc_73
		ld	hl, unk_1BF8	; 1BF8 - PWM Sound Commands
		ld	b, 8

loc_7C:					; CODE XREF: RAM:007Ej
		ld	(hl), a		; clear	PWM bytes
		inc	hl
		djnz	loc_7C
		ld	(byte_1BF7), a	; clear	driver status byte
		ld	a, 8
		ld	(byte_1C04), a	; set Song Bank	to 08 (840000)
		ld	hl, byte_1C04
		ld	a, (hl)
		ld	hl, 6000h	; switch to Song Bank
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		xor	a
		ld	(hl), a
		ld	(hl), a
		ld	(hl), 1

loc_9F:					; CODE XREF: RAM:00A2j
		ei
		nop
		nop
		jr	loc_9F

; =============== S U B	R O U T	I N E =======================================


UpdateAll:				; CODE XREF: RAM:0048p
		call	DoPause
		call	DoTempo
		call	DoFading
		call	PlaySoundID
		call	UpdateSFXTracks
		xor	a
		ld	(byte_1C19), a	; 00 - Music Mode
		ld	hl, byte_1C04
		ld	a, (hl)
		ld	hl, 6000h	; switch to Song Bank
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		xor	a
		ld	(hl), a
		ld	(hl), a
		ld	(hl), 1
		ld	ix, byte_1C40	; leftover code	(1C40 -	Music Track Drum)
		ld	b, 0Dh		; 13 Tracks (6x	FM + 3x	PSG + 4x PWM)
		ld	ix, byte_1C40	; 1C40 - Music Track FM	1
		call	TrkUpdateLoop
		call	SendPSGState
		call	SetReadyStatus
		ret
; End of function UpdateAll


; =============== S U B	R O U T	I N E =======================================


UpdateSFXTracks:			; CODE XREF: UpdateAll+Cp
		ld	a, 1
		ld	(byte_1C19), a	; 01 - SFX Mode
		ld	hl, 6000h	; switch to SFX	Bank (8D0000)
		xor	a		; Bank bits written: 11Ah
		ld	e, 1
		ld	(hl), a
		ld	(hl), e
		ld	(hl), a
		ld	(hl), e
		ld	(hl), e
		ld	(hl), a
		ld	(hl), a
		ld	(hl), a
		ld	(hl), 1
		ld	ix, unk_1EB0	; 1EB0 - SFX Tracks
		ld	b, 5		; 5 SFX	tracks
; End of function UpdateSFXTracks


; =============== S U B	R O U T	I N E =======================================


TrkUpdateLoop:				; CODE XREF: UpdateAll+34p
					; TrkUpdateLoop+Ej
		push	bc
		bit	7, (ix+0)
		call	nz, UpdateTrack
		ld	de, 30h
		add	ix, de
		pop	bc
		djnz	TrkUpdateLoop
		ret
; End of function TrkUpdateLoop


; =============== S U B	R O U T	I N E =======================================


UpdateTrack:				; CODE XREF: TrkUpdateLoop+5p

; FUNCTION CHUNK AT 028E SIZE 00000019 BYTES
; FUNCTION CHUNK AT 0D5B SIZE 0000009A BYTES
; FUNCTION CHUNK AT 0EC7 SIZE 00000068 BYTES
; FUNCTION CHUNK AT 0F33 SIZE 0000000A BYTES

		bit	7, (ix+1)	; 80/A0/C0
		jp	nz, UpdatePSGTrk
		bit	3, (ix+1)	; 18/1A/1C/1E (the bit for 08 is checked)
		jp	nz, UpdatePWMTrk
		call	TrackTimeout
		jr	nz, loc_138
		call	TrkUpdate_Proc
		bit	4, (ix+0)
		ret	nz
		call	PrepareModulat
		call	DoPitchSlide
		call	DoModulation
		call	SendFMFreq
		jp	DoNoteOn
; ---------------------------------------------------------------------------

loc_138:				; CODE XREF: UpdateTrack+11j
		call	ExecPanAnim
		bit	4, (ix+0)
		ret	nz
		call	DoFMVolEnv
		ld	a, (ix+1Eh)
		or	a
		jr	z, loc_14F
		dec	(ix+1Eh)
		jp	z, DoNoteOff

loc_14F:				; CODE XREF: UpdateTrack+39j
		call	DoPitchSlide
		bit	6, (ix+0)
		ret	nz
		call	DoModulation
; End of function UpdateTrack


; =============== S U B	R O U T	I N E =======================================


SendFMFreq:				; CODE XREF: UpdateTrack+24p
		bit	2, (ix+0)
		ret	nz
		bit	0, (ix+0)
		jp	nz, loc_16F

loc_166:				; CODE XREF: SendFMFreq+1Aj
		ld	a, 0A4h
		ld	c, h
		rst	WriteFMIorII
		ld	a, 0A0h
		ld	c, l
		rst	WriteFMIorII
		ret
; ---------------------------------------------------------------------------

loc_16F:				; CODE XREF: SendFMFreq+9j
		ld	a, (ix+1)
		cp	2
		jr	nz, loc_166
		call	GetFM3FreqPtr
		ld	b, 4
		ld	hl, SpcFM3Regs

loc_17E:				; CODE XREF: SendFMFreq+43j
		push	bc
		ld	a, (hl)
		inc	hl
		push	hl
		ex	de, hl
		ld	c, (hl)
		inc	hl
		ld	b, (hl)
		inc	hl
		ex	de, hl
		ld	l, (ix+0Dh)
		ld	h, (ix+0Eh)
		add	hl, bc
		push	af
		ld	c, h
		call	WriteFMI
		pop	af
		sub	4
		ld	c, l
		call	WriteFMI
		pop	hl
		pop	bc
		djnz	loc_17E
		ret
; End of function SendFMFreq

; ---------------------------------------------------------------------------
SpcFM3Regs:	db 0ADh, 0AEh, 0ACh, 0A6h ; DATA XREF: SendFMFreq+21o

; =============== S U B	R O U T	I N E =======================================


GetFM3FreqPtr:				; CODE XREF: SendFMFreq+1Cp
					; cfFE_SpcFM3Mode+Cp
		ld	de, unk_1C2A
		ld	a, (byte_1C19)
		or	a
		ret	z		; Music	Mode (00) - 1C2A
		ld	de, unk_1C1A
		ret	p		; Special SFX Mode (80)	- 1C1A
		ld	de, unk_1C22
		ret			; SFX Mode (01)	- 1C22
; End of function GetFM3FreqPtr


; =============== S U B	R O U T	I N E =======================================


TrkUpdate_Proc:				; CODE XREF: UpdateTrack+13p
					; UpdateTrack+C52p

; FUNCTION CHUNK AT 0999 SIZE 0000000C BYTES

		ld	e, (ix+3)
		ld	d, (ix+4)
		res	1, (ix+0)
		res	4, (ix+0)

loc_1C2:				; CODE XREF: RAM:09A6j
		ld	a, (de)
		inc	de
		cp	0E0h
		jp	nc, cfHandler
		ex	af, af'
		call	DoNoteOff
		call	DoPanAnimation
		ex	af, af'
		bit	3, (ix+0)
		jp	nz, DoRawFreqMode
		or	a
		jp	p, SetDuration	; 00-7F	- Delay
		sub	81h
		jp	p, GetNote	; 81-DF	- Note
		call	SetRest		; 80 - Rest
		jr	loc_214
; ---------------------------------------------------------------------------

GetNote:				; CODE XREF: TrkUpdate_Proc+2Aj
		add	a, (ix+5)
		ld	hl, PSGFreqs
		push	af
		rst	ReadPtrTable
		pop	af
		bit	7, (ix+1)
		jr	nz, loc_20E	; PSG channel -	jump
		push	de		; calculate FM frequency
		ld	d, 8
		ld	e, 0Ch
		ex	af, af'
		xor	a

loc_1FC:				; CODE XREF: TrkUpdate_Proc+4Ej
		ex	af, af'
		sub	e
		jr	c, loc_205
		ex	af, af'
		add	a, d
		jr	loc_1FC
; ---------------------------------------------------------------------------
		ex	af, af'         ; dead code

loc_205:				; CODE XREF: TrkUpdate_Proc+4Aj
		add	a, e
		ld	hl, FMFreqs
		rst	ReadPtrTable
		ex	af, af'
		or	h
		ld	h, a
		pop	de

loc_20E:				; CODE XREF: TrkUpdate_Proc+3Fj
		ld	(ix+0Dh), l
		ld	(ix+0Eh), h

loc_214:				; CODE XREF: TrkUpdate_Proc+30j
		bit	5, (ix+0)
		jr	nz, loc_227
		ld	a, (de)
		or	a
		jp	p, loc_253
		ld	a, (ix+0Ch)
		ld	(ix+0Bh), a
		jr	FinishTrkUpdate
; ---------------------------------------------------------------------------

loc_227:				; CODE XREF: TrkUpdate_Proc+64j
		ld	a, (de)
		inc	de
		ld	(ix+10h), a
		jr	loc_252
; ---------------------------------------------------------------------------

DoRawFreqMode:				; CODE XREF: TrkUpdate_Proc+21j
		ld	h, a
		ld	a, (de)
		inc	de
		ld	l, a
		or	h
		jr	z, loc_241
		ld	a, (ix+5)
		ld	b, 0
		or	a
		jp	p, loc_23F
		dec	b

loc_23F:				; CODE XREF: TrkUpdate_Proc+87j
		ld	c, a
		add	hl, bc

loc_241:				; CODE XREF: TrkUpdate_Proc+7Fj
		ld	(ix+0Dh), l
		ld	(ix+0Eh), h
		bit	5, (ix+0)
		jr	z, loc_252
		ld	a, (de)
		inc	de
		ld	(ix+10h), a

loc_252:				; CODE XREF: TrkUpdate_Proc+78j
					; TrkUpdate_Proc+97j
		ld	a, (de)

loc_253:				; CODE XREF: TrkUpdate_Proc+68j
		inc	de

SetDuration:				; CODE XREF: TrkUpdate_Proc+25j
		call	TickMultiplier
		ld	(ix+0Ch), a

FinishTrkUpdate:			; CODE XREF: TrkUpdate_Proc+71j
		ld	(ix+3),	e
		ld	(ix+4),	d
		ld	a, (ix+0Ch)
		ld	(ix+0Bh), a
		bit	1, (ix+0)
		ret	nz
		xor	a
		ld	(ix+25h), a
		ld	(ix+22h), a
		ld	(ix+17h), a
		ld	a, (ix+1Fh)
		ld	(ix+1Eh), a
		ret
; End of function TrkUpdate_Proc


; =============== S U B	R O U T	I N E =======================================


TickMultiplier:				; CODE XREF: TrkUpdate_Proc:SetDurationp
					; cfE8_NoteStopp ...
		ld	b, (ix+2)
		dec	b
		ret	z
		ld	c, a

loc_282:				; CODE XREF: TickMultiplier+7j
		add	a, c
		djnz	loc_282
		ret
; End of function TickMultiplier


; =============== S U B	R O U T	I N E =======================================


TrackTimeout:				; CODE XREF: UpdateTrack+Ep
					; UpdateTrack:UpdatePSGTrkp ...
		ld	a, (ix+0Bh)
		dec	a
		ld	(ix+0Bh), a
		ret
; End of function TrackTimeout

; ---------------------------------------------------------------------------
; START	OF FUNCTION CHUNK FOR UpdateTrack

DoNoteOn:				; CODE XREF: UpdateTrack+27j
		ld	a, (ix+0Dh)
		or	(ix+0Eh)
		ret	z
		ld	a, (ix+0)
		and	6
		ret	nz
		ld	a, (ix+1)
		or	0F0h
		ld	c, a
		ld	a, 28h
		call	WriteFMI
		ret
; END OF FUNCTION CHUNK	FOR UpdateTrack

; =============== S U B	R O U T	I N E =======================================


DoNoteOff:				; CODE XREF: UpdateTrack+3Ej
					; TrkUpdate_Proc+16p ...
		ld	a, (ix+0)
		and	6
		ret	nz

SendNoteOff:				; CODE XREF: cf02_MusPause+16p
		ld	c, (ix+1)
		bit	7, c
		ret	nz
; End of function DoNoteOff

; START	OF FUNCTION CHUNK FOR SilenceFMChn

FMNoteOff:				; CODE XREF: SilenceFMChn+Dj
		ld	a, 28h
		call	WriteFMI
		res	6, (ix+0)
		ret
; END OF FUNCTION CHUNK	FOR SilenceFMChn

; =============== S U B	R O U T	I N E =======================================


DoPanAnimation:				; CODE XREF: TrkUpdate_Proc+19p
		ld	a, (ix+11h)
		dec	a
		ret	m
		jr	nz, loc_303
		bit	1, (ix+0)
		ret	nz

loc_2C9:				; CODE XREF: ExecPanAnim+6j
		dec	(ix+16h)
		ret	nz
		push	bc
		push	de
		push	hl
		ld	a, (ix+15h)
		ld	(ix+16h), a
		ld	a, (ix+12h)
		ld	hl, PanAniPtrList
		rst	ReadPtrTable
		ld	e, (ix+13h)
		inc	(ix+13h)
		ld	a, (ix+14h)
		dec	a
		cp	e
		jr	nz, loc_2F8
		dec	(ix+13h)
		ld	a, (ix+11h)
		cp	2
		jr	z, loc_2F8
		ld	(ix+13h), 0

loc_2F8:				; CODE XREF: DoPanAnimation+2Bj
					; DoPanAnimation+35j
		ld	d, 0
		add	hl, de
		ex	de, hl
		call	cfE0_Pan
		pop	hl
		pop	de
		pop	bc
		ret
; ---------------------------------------------------------------------------

loc_303:				; CODE XREF: DoPanAnimation+5j
		xor	a
		ld	(ix+13h), a
; End of function DoPanAnimation


; =============== S U B	R O U T	I N E =======================================


ExecPanAnim:				; CODE XREF: UpdateTrack:loc_138p
		ld	a, (ix+11h)
		sub	2
		ret	m
		jr	loc_2C9
; End of function ExecPanAnim

; ---------------------------------------------------------------------------
PanAniPtrList:	dw byte_317, byte_318, byte_319, byte_31A ; DATA XREF: DoPanAnimation+1Co
byte_317:	db 0C0h			; DATA XREF: RAM:PanAniPtrListo
byte_318:	db 80h			; DATA XREF: RAM:PanAniPtrListo
byte_319:	db 0C0h			; DATA XREF: RAM:PanAniPtrListo
byte_31A:	db 40h,	0C0h, 80h	; DATA XREF: RAM:PanAniPtrListo

; =============== S U B	R O U T	I N E =======================================


DoFMVolEnv:				; CODE XREF: UpdateTrack+32p
		ld	a, (ix+18h)
		or	a
		ret	z
		ret	m
		dec	a
		ld	hl, (VolEnvListPtr)
		rst	ReadPtrTable
		call	DoPSGVolEnv
		ld	h, (ix+1Dh)
		ld	l, (ix+1Ch)
		ld	de, Volume_Ops
		ld	b, 4
		ld	c, (ix+19h)

loc_339:				; CODE XREF: DoFMVolEnv+2Cj
		push	af
		sra	c
		push	bc
		jr	nc, loc_345
		add	a, (hl)
		and	7Fh
		ld	c, a
		ld	a, (de)
		rst	WriteFMIorII

loc_345:				; CODE XREF: DoFMVolEnv+20j
		pop	bc
		inc	de
		inc	hl
		pop	af
		djnz	loc_339
		ret
; End of function DoFMVolEnv


; =============== S U B	R O U T	I N E =======================================


PrepareModulat:				; CODE XREF: UpdateTrack+1Bp
					; UpdateTrack+C5Ap
		bit	7, (ix+7)
		ret	z
		bit	1, (ix+0)
		ret	nz
		ld	e, (ix+20h)
		ld	d, (ix+21h)
		push	ix
		pop	hl
		ld	b, 0
		ld	c, 24h
		add	hl, bc
		ex	de, hl
		ldi
		ldi
		ldi
		ld	a, (hl)
		srl	a
		ld	(de), a
		xor	a
		ld	(ix+22h), a
		ld	(ix+23h), a
		ret
; End of function PrepareModulat


; =============== S U B	R O U T	I N E =======================================


DoModulation:				; CODE XREF: UpdateTrack+21p
					; UpdateTrack+49p ...
		ld	a, (ix+7)
		or	a
		ret	z		; ModType 00 ->	return (modulation off)
		cp	80h
		jr	nz, DoModulatEnv ; ModType != 80 -> jump
		dec	(ix+24h)	; ModType 80 ->	manual modulation parameters
		ret	nz
		inc	(ix+24h)
		push	hl
		ld	l, (ix+22h)
		ld	h, (ix+23h)
		ld	e, (ix+20h)
		ld	d, (ix+21h)
		push	de
		pop	iy
		dec	(ix+25h)
		jr	nz, loc_3B3
		ld	a, (iy+1)
		ld	(ix+25h), a
		ld	a, (ix+26h)
		ld	c, a
		and	80h
		rlca
		neg
		ld	b, a
		add	hl, bc
		ld	(ix+22h), l
		ld	(ix+23h), h

loc_3B3:				; CODE XREF: DoModulation+23j
		pop	bc
		add	hl, bc
		dec	(ix+27h)
		ret	nz
		ld	a, (iy+3)
		ld	(ix+27h), a
		ld	a, (ix+26h)
		neg
		ld	(ix+26h), a
		ret
; ---------------------------------------------------------------------------

DoModulatEnv:				; CODE XREF: DoModulation+7j
		dec	a
		ex	de, hl
		ld	hl, (ModEnvListPtr)
		rst	ReadPtrTable
		jr	loc_3D3
; ---------------------------------------------------------------------------

loc_3D0:				; CODE XREF: DoModulation+82j
					; DoModulation+85j
		ld	(ix+25h), a

loc_3D3:				; CODE XREF: DoModulation+57j
					; DoModulation+95j
		push	hl
		ld	c, (ix+25h)
		ld	b, 0
		add	hl, bc
		ld	a, (hl)
		pop	hl
		bit	7, a
		jp	z, ModEnv_Positive
		cp	82h
		jr	z, ModEnv_Jump2Idx ; 82	xx - jump to byte xx
		cp	80h
		jr	z, ModEnv_Reset	; 80 - loop back to beginning
		cp	84h
		jr	z, ModEnv_ChgMult ; 84 - change	Modulation Multipler
		ld	h, 0FFh		; make HL negative (FFxx)
		jr	nc, ModEnv_Next
		set	6, (ix+0)
		pop	hl
		ret
; ---------------------------------------------------------------------------

ModEnv_Jump2Idx:			; CODE XREF: DoModulation+6Cj
		inc	bc
		ld	a, (bc)
		jr	loc_3D0
; ---------------------------------------------------------------------------

ModEnv_Reset:				; CODE XREF: DoModulation+70j
		xor	a
		jr	loc_3D0
; ---------------------------------------------------------------------------

ModEnv_ChgMult:				; CODE XREF: DoModulation+74j
		inc	bc
		ld	a, (bc)
		add	a, (ix+22h)
		ld	(ix+22h), a
		inc	(ix+25h)
		inc	(ix+25h)
		jr	loc_3D3
; ---------------------------------------------------------------------------

ModEnv_Positive:			; CODE XREF: DoModulation+67j
		ld	h, 0		; make HL positive (00xx)

ModEnv_Next:				; CODE XREF: DoModulation+78j
		ld	l, a
		ld	b, (ix+22h)
		inc	b
		ex	de, hl

loc_416:				; CODE XREF: DoModulation+A0j
		add	hl, de
		djnz	loc_416
		inc	(ix+25h)
		ret
; End of function DoModulation


; =============== S U B	R O U T	I N E =======================================


DoPitchSlide:				; CODE XREF: UpdateTrack+1Ep
					; UpdateTrack:loc_14Fp	...
		ld	b, 0
		ld	a, (ix+10h)
		or	a
		jp	p, loc_427
		dec	b

loc_427:				; CODE XREF: DoPitchSlide+6j
		ld	h, (ix+0Eh)
		ld	l, (ix+0Dh)
		ld	c, a
		add	hl, bc
		bit	7, (ix+1)
		jr	nz, loc_457
		ex	de, hl
		ld	a, 7
		and	d
		ld	b, a
		ld	c, e
		or	a
		ld	hl, 283h
		sbc	hl, bc
		jr	c, loc_449
		ld	hl, -57Bh
		add	hl, de
		jr	loc_457
; ---------------------------------------------------------------------------

loc_449:				; CODE XREF: DoPitchSlide+24j
		or	a
		ld	hl, 508h
		sbc	hl, bc
		jr	nc, loc_456
		ld	hl, 57Ch
		add	hl, de
		ex	de, hl

loc_456:				; CODE XREF: DoPitchSlide+32j
		ex	de, hl

loc_457:				; CODE XREF: DoPitchSlide+16j
					; DoPitchSlide+2Aj
		bit	5, (ix+0)
		ret	z
		ld	(ix+0Eh), h
		ld	(ix+0Dh), l
		ret
; End of function DoPitchSlide


; =============== S U B	R O U T	I N E =======================================


GetFMInsPtr:				; CODE XREF: SetInsFromSong+1Bp
		ld	hl, (word_1C37)
		ld	a, (byte_1C19)
		or	a
		jr	z, JumpToInsData ; Mode	00 (Music Mode)	- jump
		ld	l, (ix+2Ah)	; load SFX track Instrument Pointer (Trk+2A/2B)
		ld	h, (ix+2Bh)
; End of function GetFMInsPtr


; =============== S U B	R O U T	I N E =======================================


JumpToInsData:				; CODE XREF: GetFMInsPtr+7j
					; SetInsFromSong+14p ...
		xor	a
		or	b
		ret	z
		ld	de, 19h

loc_478:				; CODE XREF: JumpToInsData+7j
		add	hl, de
		djnz	loc_478
		ret
; End of function JumpToInsData

; ---------------------------------------------------------------------------
FMInsOperators:	db 0B0h			; DATA XREF: SendFMInso
		db  30h, 38h, 34h, 3Ch
		db  50h, 58h, 54h, 5Ch
		db  60h, 68h, 64h, 6Ch
		db  70h, 78h, 74h, 7Ch
		db  80h, 88h, 84h, 8Ch
Volume_Ops:	db  40h, 48h, 44h, 4Ch	; DATA XREF: DoFMVolEnv+14o
					; RefreshVolume+1o
SSGEG_Regs:	db  90h, 98h, 94h, 9Ch	; DATA XREF: SendSSGEGo

; =============== S U B	R O U T	I N E =======================================


SendFMIns:				; CODE XREF: SetInsFromSong:loc_B05p
					; cfE3_SilenceTrk+184p
		ld	de, FMInsOperators
		ld	c, (ix+0Ah)
		ld	a, 0B4h
		rst	WriteFMIorII
		call	WriteInsReg
		ld	(ix+1Bh), a
		ld	b, 14h

loc_4AA:				; CODE XREF: SendFMIns+14j
		call	WriteInsReg
		djnz	loc_4AA
		ld	(ix+1Ch), l
		ld	(ix+1Dh), h
		jp	RefreshVolume
; End of function SendFMIns


; =============== S U B	R O U T	I N E =======================================


WriteInsReg:				; CODE XREF: SendFMIns+9p
					; SendFMIns:loc_4AAp
		ld	a, (de)
		inc	de
		ld	c, (hl)
		inc	hl
		rst	WriteFMIorII
		ret
; End of function WriteInsReg


; =============== S U B	R O U T	I N E =======================================


PlaySoundID:				; CODE XREF: UpdateAll+9p

; FUNCTION CHUNK AT 05FD SIZE 000000A2 BYTES

		ld	a, (byte_1C09)	; read Sound ID
		cp	2Ah
		jp	c, PlayMusic	; 00-29	- Music
		cp	6Fh
		jp	c, PlaySFX	; 2A-6E	- SFX
		cp	0F0h
		jp	c, StopAllSound	; 6F-EF	- Stop All
		cp	0FFh
		jp	nc, StopAllSound ; FF -	Stop All

PlaySnd_Command:			; F0-FE	- Control Commands
		sub	0F0h
		ld	hl, CmdPtrTable
		rst	ReadPtrTable
		xor	a
		ld	(byte_1C18), a	; reset	current	Sound Priority
		jp	(hl)
; ---------------------------------------------------------------------------
CmdPtrTable:				; DATA XREF: PlaySoundID+19o
		dw FadeOutMusic, StopAllSound, PSGSilenceAll
		dw FadeOutMusic, StopAllSound, PSGSilenceAll
		dw FadeOutMusic, StopAllSound, PSGSilenceAll
		dw FadeOutMusic, StopAllSound, PSGSilenceAll
		dw FadeOutMusic, StopAllSound, PSGSilenceAll
		dw StopAllSound
; ---------------------------------------------------------------------------

PlayMusic:				; CODE XREF: PlaySoundID+5j
		or	a
		ret	z
		dec	a
		ex	af, af'
		call	StopAllSound
		ex	af, af'
		push	af
		ld	hl, (SongBankPtr)
		add	a, l
		ld	l, a
		adc	a, h
		sub	l
		ld	h, a
		ld	a, (hl)
		ld	(byte_1C04), a
		ld	hl, byte_1C04
		ld	a, (hl)
		ld	hl, 6000h	; switch to Song Bank
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		xor	a
		ld	(hl), a
		ld	(hl), a
		ld	(hl), 1
		pop	af
		ld	hl, (MusListPtr)
		rst	ReadPtrTable
		push	hl
		push	hl
		ld	a, (hl)
		inc	hl
		ld	h, (hl)
		ld	l, a
		ld	(word_1C37), hl
		pop	hl
		pop	iy
		ld	a, (iy+5)
		ld	(byte_1C13), a
		ld	(byte_1C14), a
		ld	de, 6
		add	hl, de
		ld	(word_1C33), hl
		ld	hl, FMInitBytes
		ld	(word_1C35), hl
		ld	de, byte_1C40
		ld	b, (iy+2)	; load FM tracks
		ld	a, (iy+4)	; load Tick Multipler

loc_55C:				; CODE XREF: PlaySoundID+BDj
		push	bc
		ld	hl, (word_1C35)
		ldi
		ldi
		ld	(de), a
		inc	de
		ld	(word_1C35), hl
		ld	hl, (word_1C33)
		ldi
		ldi
		ldi
		ldi
		ld	(word_1C33), hl
		call	FinishFMTrkInit
		pop	bc
		djnz	loc_55C
		ld	a, (iy+3)	; load PSG tracks
		or	a
		jp	z, ClearSoundID
		ld	b, a
		ld	hl, PSGInitBytes
		ld	(word_1C35), hl
		ld	de, byte_1D60
		ld	a, (iy+4)

loc_591:				; CODE XREF: PlaySoundID+EFj
		push	bc
		ld	hl, (word_1C35)
		ldi
		ldi
		ld	(de), a
		inc	de
		ld	(word_1C35), hl
		ld	hl, (word_1C33)
		ld	bc, 6
		ldir
		ld	(word_1C33), hl
		call	FinishTrkInit
		pop	bc
		djnz	loc_591
		ld	hl, PWMInitBytes
		ld	(word_1C35), hl
		ld	de, byte_1DF0
		ld	a, (iy+4)
		ld	b, 4

loc_5BD:				; CODE XREF: PlaySoundID+11Ej
		push	bc
		ld	hl, (word_1C35)
		ldi
		ldi
		ld	(de), a
		inc	de
		ld	(word_1C35), hl
		ld	hl, (word_1C33)
		ldi
		ldi
		ldi
		ldi
		ld	(word_1C33), hl
		call	FinishFMTrkInit
		pop	bc
		djnz	loc_5BD
; End of function PlaySoundID

; START	OF FUNCTION CHUNK FOR StopAllSound

ClearSoundID:				; CODE XREF: PlaySoundID+C3j
					; PlaySoundID+1DEj ...
		xor	a
		ld	(byte_1C09), a
		ret
; END OF FUNCTION CHUNK	FOR StopAllSound
; ---------------------------------------------------------------------------
FMInitBytes:	db  80h,   0		; DATA XREF: PlaySoundID+8Fo
					; StopAllSound+Do
		db  80h,   1
		db  80h,   2
		db  80h,   4
		db  80h,   5
		db  80h,   6
PSGInitBytes:	db  80h, 80h		; DATA XREF: PlaySoundID+C7o
		db  80h,0A0h
		db  80h,0C0h
PWMInitBytes:	db  80h, 18h		; DATA XREF: PlaySoundID+F1o
		db  80h, 1Ah
		db  80h, 1Ch
		db  80h, 1Eh
; ---------------------------------------------------------------------------
; START	OF FUNCTION CHUNK FOR PlaySoundID

PlaySFX:				; CODE XREF: PlaySoundID+Aj
		ex	af, af'
		ld	hl, 6000h
		xor	a
		ld	e, 1		; set Bank 8D0000
		ld	(hl), a
		ld	(hl), e
		ld	(hl), a
		ld	(hl), e
		ld	(hl), e
		ld	(hl), a
		ld	(hl), a
		ld	(hl), a
		ld	(hl), 1
		ex	af, af'
		sub	2Ah		; Sound	ID -> SFX Index
		ex	af, af'
		xor	a
		ld	hl, (SFXListPtr)
		ld	(byte_1C19), a
		ex	af, af'
		rst	ReadPtrTable
		push	hl
		ld	a, (hl)
		inc	hl
		ld	h, (hl)
		ld	l, a
		ld	(word_1C39), hl
		xor	a
		ld	(byte_1C15), a
		pop	hl
		push	hl
		pop	iy
		ld	a, (iy+2)
		ld	(byte_1C3B), a
		ld	de, 4
		add	hl, de
		ld	b, (iy+3)

SFXTrkInitLoop:				; CODE XREF: PlaySoundID+1DCj
		push	bc
		push	hl
		inc	hl
		ld	c, (hl)
		call	GetSFXChnPtrs
		set	2, (hl)
		push	ix
		ld	a, (byte_1C19)
		or	a
		jr	z, loc_64C
		pop	hl
		push	iy

loc_64C:				; CODE XREF: PlaySoundID+189j
		pop	de
		pop	hl
		ldi
		ld	a, (de)
		cp	2
		call	z, ResetSpcFM3Mode
		ldi
		ld	a, (byte_1C3B)
		ld	(de), a
		inc	de
		ldi
		ldi
		ldi
		ldi
		call	FinishFMTrkInit
		bit	7, (ix+0)
		jr	z, loc_67A
		ld	a, (ix+1)
		cp	(iy+1)
		jr	nz, loc_67A
		set	2, (iy+0)

loc_67A:				; CODE XREF: PlaySoundID+1AEj
					; PlaySoundID+1B6j
		push	hl
		ld	hl, (word_1C39)
		ld	a, (byte_1C19)
		or	a
		jr	z, loc_688
		push	iy
		pop	ix

loc_688:				; CODE XREF: PlaySoundID+1C4j
		ld	(ix+2Ah), l
		ld	(ix+2Bh), h
		call	DoNoteOff
		bit	7, (ix+1)
		call	z, DisableSSGEG
		pop	hl
		pop	bc
		djnz	SFXTrkInitLoop
		jp	ClearSoundID
; END OF FUNCTION CHUNK	FOR PlaySoundID

; =============== S U B	R O U T	I N E =======================================


GetSFXChnPtrs:				; CODE XREF: PlaySoundID+17Ep
					; cfE3_SilenceTrk+123p
		bit	7, c
		jr	nz, loc_6AB
		ld	a, c
		bit	2, a
		jr	z, loc_6C4
		dec	a
		jr	loc_6C4
; ---------------------------------------------------------------------------

loc_6AB:				; CODE XREF: GetSFXChnPtrs+2j
		ld	a, 1Fh
		push	bc
		call	SilencePSGChn
		pop	bc
		ld	a, 0FFh
		ld	(PSGState_Ch4+2), a
		ld	a, c
		srl	a
		srl	a
		srl	a
		srl	a
		srl	a
		add	a, 2

loc_6C4:				; CODE XREF: GetSFXChnPtrs+7j
					; GetSFXChnPtrs+Aj
		sub	2
		ld	(byte_1C32), a
		push	af
		ld	hl, SFXChnPtrs
		rst	ReadPtrTable
		push	hl
		pop	ix		; IX - SFX Track
		pop	af
		ld	hl, BGMChnPtrs
		rst	ReadPtrTable	; HL - Music Track
		ret
; End of function GetSFXChnPtrs


; =============== S U B	R O U T	I N E =======================================


FinishFMTrkInit:			; CODE XREF: PlaySoundID+B9p
					; PlaySoundID+11Ap ...
		ex	af, af'
		xor	a
		ld	(de), a
		inc	de
		ld	(de), a
		inc	de
		ex	af, af'
; End of function FinishFMTrkInit


; =============== S U B	R O U T	I N E =======================================


FinishTrkInit:				; CODE XREF: PlaySoundID+EBp
		ex	de, hl
		ld	(hl), 30h
		inc	hl
		ld	(hl), 0C0h
		inc	hl
		ld	(hl), 1
		ld	b, 24h

loc_6E9:				; CODE XREF: FinishTrkInit+Ej
		inc	hl
		ld	(hl), 0
		djnz	loc_6E9
		inc	hl
		ex	de, hl
		ret
; End of function FinishTrkInit

; ---------------------------------------------------------------------------
SFXChnPtrs:	dw 1EB0h, 1EB0h, 1EE0h,	1F10h, 1F40h, 1F40h, 1F70h, 1F70h
					; DATA XREF: GetSFXChnPtrs+2Bo
BGMChnPtrs:	dw 1CD0h, 1CD0h, 1D00h,	1D30h, 1D90h, 1D90h, 1DC0h, 1DC0h
					; DATA XREF: GetSFXChnPtrs+33o

; =============== S U B	R O U T	I N E =======================================


DoPause:				; CODE XREF: UpdateAllp

; FUNCTION CHUNK AT 0814 SIZE 00000033 BYTES

		ld	hl, unk_1C10	; 1C10 = Pause Mode
		ld	a, (hl)
		or	a
		ret	z		; 00 = not paused
		jp	m, UnpauseMusic	; 80-FF	- request Unpause
		pop	de
		dec	a		; 01 - request Pause?
		ret	nz		; no, it's 02 - return
		ld	(hl), 2		; it's 01, so set it to 02 (Pause active)
		jp	SilenceAll
; ---------------------------------------------------------------------------

UnpauseMusic:				; CODE XREF: DoPause+6j
		xor	a
		ld	(hl), a
		ld	a, (byte_1C0D)
		or	a
		jp	nz, StopAllSound
		ld	ix, byte_1C40	; IX = Track of	FM 1
		ld	b, 6

loc_731:				; CODE XREF: DoPause+37j
		ld	a, (byte_1C11)
		or	a
		jr	nz, loc_73D
		bit	7, (ix+0)
		jr	z, loc_743

loc_73D:				; CODE XREF: DoPause+24j
		ld	c, (ix+0Ah)
		ld	a, 0B4h
		rst	WriteFMIorII

loc_743:				; CODE XREF: DoPause+2Aj
		ld	de, 30h
		add	ix, de
		djnz	loc_731
		ld	ix, unk_1EB0	; 1EB0 - SFX Tracks
		ld	b, 5

loc_750:				; CODE XREF: DoPause+56j
		bit	7, (ix+0)
		jr	z, loc_762
		bit	7, (ix+1)
		jr	nz, loc_762
		ld	c, (ix+0Ah)
		ld	a, 0B4h
		rst	WriteFMIorII

loc_762:				; CODE XREF: DoPause+43j DoPause+49j
		ld	de, 30h
		add	ix, de
		djnz	loc_750
		ret
; End of function DoPause

; ---------------------------------------------------------------------------

FadeOutMusic:				; DATA XREF: PlaySoundID:CmdPtrTableo
		ld	a, 28h		; Number of fading steps
		ld	(byte_1C0D), a
		ld	a, 6		; Frames per Step
		ld	(byte_1C0F), a
		ld	(byte_1C0E), a

; =============== S U B	R O U T	I N E =======================================


StopDrumPSG:				; CODE XREF: DoFading+6p
		xor	a
		ld	(byte_1D60), a	; stop PSG2 Track
		ld	(byte_1D90), a	; stop PSG3 Track
		jp	PSGSilenceAll
; End of function StopDrumPSG


; =============== S U B	R O U T	I N E =======================================


DoFading:				; CODE XREF: UpdateAll+6p
		ld	hl, byte_1C0D
		ld	a, (hl)		; load remaining Fading	Steps
		or	a
		ret	z		; reached 0 - return
		call	m, StopDrumPSG	; 80+ -	mute Drum and PSG channels
		res	7, (hl)
		ld	a, (byte_1C0F)	; 1C0F - Timeout Counter
		dec	a
		jr	z, ApplyFading	; reached 0 - apply fading
		ld	(byte_1C0F), a	; else just write back
		ret
; ---------------------------------------------------------------------------

ApplyFading:				; CODE XREF: DoFading+Fj
		ld	a, (byte_1C0E)
		ld	(byte_1C0F), a
		ld	a, (byte_1C0D)
		dec	a
		ld	(byte_1C0D), a
		jr	z, StopAllSound
		ld	hl, byte_1C06
		inc	(hl)		; increment Fade volume
		ld	ix, byte_1C40
		ld	b, 6

loc_7AF:				; CODE XREF: DoFading+44j
		bit	7, (ix+0)
		jr	z, loc_7C0
		bit	2, (ix+0)
		jr	nz, loc_7C0
		push	bc
		call	RefreshVolume
		pop	bc

loc_7C0:				; CODE XREF: DoFading+32j DoFading+38j
		ld	de, 30h
		add	ix, de
		djnz	loc_7AF
		ret
; End of function DoFading


; =============== S U B	R O U T	I N E =======================================


StopAllSound:				; CODE XREF: RAM:0067p	PlaySoundID+Fj	...

; FUNCTION CHUNK AT 05DE SIZE 00000005 BYTES

		ld	hl, byte_1C09
		ld	de, byte_1C0A
		ld	bc, 396h
		ld	(hl), 0
		ldir
		ld	ix, FMInitBytes
		ld	b, 6

loc_7DB:				; CODE XREF: StopAllSound+1Fj
		push	bc
		call	SilenceFMChn
		call	DisableSSGEG
		inc	ix
		inc	ix
		pop	bc
		djnz	loc_7DB
		ld	b, 7
		xor	a
		ld	(byte_1BF7), a	; clear	driver status byte
		ld	(byte_1C06), a	; reset	Fade volume
		ld	(byte_1C0D), a	; clear	Fading Step Counter
		call	PSGSilenceAll
		ld	c, 0
		ld	a, 2Bh
		call	WriteFMI	; disable DAC

ResetSpcFM3Mode:			; CODE XREF: PlaySoundID+195p
		ld	a, 0Fh
		ld	(byte_1C12), a	; disable Ch3 special mode
		ld	c, a
		ld	a, 27h
		call	WriteFMI
		jp	ClearSoundID
; End of function StopAllSound


; =============== S U B	R O U T	I N E =======================================


DisableSSGEG:				; CODE XREF: PlaySoundID+1D7p
					; StopAllSound+17p
		ld	a, 90h
		ld	c, 0
		jp	SendAllFMOps
; End of function DisableSSGEG

; ---------------------------------------------------------------------------
; START	OF FUNCTION CHUNK FOR DoPause

SilenceAll:				; CODE XREF: DoPause+Ej
		call	PSGSilenceAll
		call	SendPSGState
		push	bc
		push	af
		ld	b, 3
		ld	a, 0B4h
		ld	c, 0

loc_822:				; CODE XREF: DoPause+117j
		push	af
		call	WriteFMI
		pop	af
		inc	a
		djnz	loc_822
		ld	b, 3
		ld	a, 0B4h

loc_82E:				; CODE XREF: DoPause+123j
		push	af
		call	WriteFMII
		pop	af
		inc	a
		djnz	loc_82E
		ld	c, 0
		ld	b, 7
		ld	a, 28h

loc_83C:				; CODE XREF: DoPause+131j
		push	af
		call	WriteFMI
		inc	c
		pop	af
		djnz	loc_83C
		pop	af
		pop	bc
		ret
; END OF FUNCTION CHUNK	FOR DoPause

; =============== S U B	R O U T	I N E =======================================


PSGSilenceAll:				; CODE XREF: StopDrumPSG+7j
					; StopAllSound+2Dp ...
		push	bc
		push	hl
		push	de
		ld	b, 4
		ld	a, 9Fh
		ld	hl,  PSGState_Ch1+2
		ld	de, 4

loc_854:				; CODE XREF: PSGSilenceAll+11j
		ld	(hl), a
		add	a, 20h
		add	hl, de
		djnz	loc_854
		pop	de
		pop	hl
		pop	bc
		jp	ClearSoundID
; End of function PSGSilenceAll


; =============== S U B	R O U T	I N E =======================================


DoTempo:				; CODE XREF: UpdateAll+3p
		ld	a, (byte_1C14)	; get Tempo Increment
		ld	hl, byte_1C13
		add	a, (hl)		; add current Tempo Counter
		ld	(hl), a		; and write it back
		ret	nc		; Addition didn't overflow - return
					; If it	did, delay all Music Tracks by 1 frame.
		ld	hl,  byte_1C40+0Bh ; 1C40 (Drum	Track) + 0B (Note Timeout)
		ld	de, 30h
		ld	b, 0Dh		; 13 Music Tracks

loc_871:				; CODE XREF: DoTempo+13j
		inc	(hl)		; delay	by 1 frame
		add	hl, de
		djnz	loc_871
		ret
; End of function DoTempo


; =============== S U B	R O U T	I N E =======================================


DoSoundQueue:				; CODE XREF: RAM:0045p
		ld	a, r
		ld	(byte_1C17), a
		ld	de, byte_1C0A
		ld	b, 3

loc_880:				; CODE XREF: DoSoundQueue+31j
		ld	a, (de)
		ld	c, a
		or	a
		jr	z, loc_8A4
		jp	m, DequeueSound
		sub	2Ah
		jr	c, DequeueSound
		ld	hl, (SndPrioPtr)
		add	a, l
		ld	l, a
		adc	a, h
		sub	l
		ld	h, a
		ld	a, (byte_1C18)
		cp	(hl)
		jr	z, loc_89C
		jr	nc, loc_8A4

loc_89C:				; CODE XREF: DoSoundQueue+22j
		ld	a, c
		ld	(byte_1C09), a
		ld	a, (hl)
		ld	(byte_1C18), a

loc_8A4:				; CODE XREF: DoSoundQueue+Dj
					; DoSoundQueue+24j
		xor	a
		ld	(de), a
		inc	de
		djnz	loc_880
		ret
; ---------------------------------------------------------------------------

DequeueSound:				; CODE XREF: DoSoundQueue+Fj
					; DoSoundQueue+14j
		ld	a, c
		ld	(byte_1C09), a
		xor	a
		ld	(byte_1C18), a
		ld	de, byte_1C0A
		ld	(de), a
		inc	de
		ld	(de), a
		inc	de
		ld	(de), a
		ret
; End of function DoSoundQueue


; =============== S U B	R O U T	I N E =======================================


SilenceFMChn:				; CODE XREF: StopAllSound+14p
					; cfE3_SilenceTrkp

; FUNCTION CHUNK AT 02B3 SIZE 0000000A BYTES

		call	SetMaxRelRate
		ld	a, 40h
		ld	c, 7Fh
		call	SendAllFMOps
		ld	c, (ix+1)
		jp	FMNoteOff
; End of function SilenceFMChn


; =============== S U B	R O U T	I N E =======================================


SetMaxRelRate:				; CODE XREF: SilenceFMChnp
					; cfEF_SetFMIns+6p
		ld	a, 80h
		ld	c, 0FFh
; End of function SetMaxRelRate


; =============== S U B	R O U T	I N E =======================================


SendAllFMOps:				; CODE XREF: DisableSSGEG+4j
					; SilenceFMChn+7p
		ld	b, 4

loc_8D1:				; CODE XREF: SendAllFMOps+7j
		push	af
		rst	WriteFMIorII
		pop	af
		add	a, 4
		djnz	loc_8D1
		ret
; End of function SendAllFMOps

; ---------------------------------------------------------------------------
PSGFreqs:	dw  3FFh, 3FFh,	3FFh, 3FFh, 3FFh, 3FFh,	3FFh, 3FFh, 3FFh, 3F7h,	3BEh, 388h
					; DATA XREF: TrkUpdate_Proc+35o
		dw  356h, 326h,	2F9h, 2CEh, 2A5h, 280h,	25Ch, 23Ah, 21Ah, 1FBh,	1DFh, 1C4h
		dw  1ABh, 193h,	17Dh, 167h, 153h, 140h,	12Eh, 11Dh, 10Dh, 0FEh,	0EFh, 0E2h
		dw  0D6h, 0C9h,	0BEh, 0B4h, 0A9h, 0A0h,	 97h,  8Fh,  87h,  7Fh,	 78h,  71h
		dw   6Bh,  65h,	 5Fh,  5Ah,  55h,  50h,	 4Bh,  47h,  43h,  40h,	 3Ch,  39h
		dw   36h,  33h,	 30h,  2Dh,  2Bh,  28h,	 26h,  24h,  22h,  20h,	 1Fh,  1Dh
		dw   1Bh,  1Ah,	 18h,  17h,  16h,  15h,	 13h,  12h,  11h,  10h,	   0,	 0
FMFreqs:	dw  284h, 2ABh,	2D3h, 2FEh, 32Dh, 35Ch,	38Fh, 3C5h, 3FFh, 43Ch,	47Ch, 4C0h
					; DATA XREF: TrkUpdate_Proc+52o
; ---------------------------------------------------------------------------
; START	OF FUNCTION CHUNK FOR TrkUpdate_Proc

cfHandler:				; CODE XREF: TrkUpdate_Proc+12j
		ld	hl, cfReturn

cfHandler_JmpIn:			; CODE XREF: UpdateTrack+DD3j
		push	hl
		sub	0E0h
		ld	hl, cfPtrTable
		rst	ReadPtrTable
		ld	a, (de)
		jp	(hl)
; END OF FUNCTION CHUNK	FOR TrkUpdate_Proc
; ---------------------------------------------------------------------------

cfReturn:				; DATA XREF: TrkUpdate_Proc:cfHandlero
		inc	de
		jp	loc_1C2
; ---------------------------------------------------------------------------
cfPtrTable:	dw cfE0_Pan, cfE1_Detune, cfE2_SetComm,	cfE3_SilenceTrk
					; DATA XREF: TrkUpdate_Proc+7EBo
		dw cfE4_PanAnim, cfE5_ChgPFMVol, cfE6_ChgFMVol,	cfE7_Hold
		dw cfE8_NoteStop, cfE9_SetLFO, cfEA_Dummy, cfEB_LoopExit
		dw cfEC_ChgPSGVol, cfED_FMChnWrite, cfEE_FM1Write, cfEF_SetFMIns
		dw cfF0_ModSetup, cfF1_ModTypePFM, cfF2_StopTrk, cfF3_PSGNoise
		dw cfF4_ModType, cfF5_SetPSGIns, cfF6_GoTo, cfF7_Loop
		dw cfF8_GoSub, cfF9_Return, cfFA_TickMult, cfFB_ChgTransp
		dw cfFC_PitchSlide, cfFD_RawFrqMode, cfFE_SpcFM3Mode, cfMetaCoordFlag
cfMetaPtrTable:	dw cf00_SetTempo, cf01_PlaySnd,	cf02_MusPause, cf03_CopyMem
					; DATA XREF: cfMetaCoordFlago
		dw cf04_TickMulAll, cf05_SSGEG,	cf06_FMVolEnv

; =============== S U B	R O U T	I N E =======================================


cfEA_Dummy:				; DATA XREF: RAM:cfPtrTableo
		dec	de
		ret
; End of function cfEA_Dummy


; =============== S U B	R O U T	I N E =======================================


cfE0_Pan:				; CODE XREF: DoPanAnimation+3Fp
					; DATA XREF: RAM:cfPtrTableo
		ld	c, 3Fh

loc_9FB:				; CODE XREF: cfE9_SetLFO+9j
		ld	a, (ix+0Ah)
		and	c
		ex	de, hl
		or	(hl)
		ld	(ix+0Ah), a
		ld	c, a
		ld	a, 0B4h
		rst	WriteFMIorII
		ex	de, hl
		ret
; End of function cfE0_Pan


; =============== S U B	R O U T	I N E =======================================


cfE9_SetLFO:				; DATA XREF: RAM:cfPtrTableo
		ld	c, a
		ld	a, 22h
		call	WriteFMI
		inc	de
		ld	c, 0C0h
		jr	loc_9FB
; End of function cfE9_SetLFO


; =============== S U B	R O U T	I N E =======================================


cfE1_Detune:				; DATA XREF: RAM:cfPtrTableo
		ld	(ix+10h), a
		ret
; End of function cfE1_Detune


; =============== S U B	R O U T	I N E =======================================


cfE2_SetComm:				; DATA XREF: RAM:cfPtrTableo
		ld	(byte_1C16), a
		ret
; End of function cfE2_SetComm


; =============== S U B	R O U T	I N E =======================================


cfE3_SilenceTrk:			; DATA XREF: RAM:cfPtrTableo

; FUNCTION CHUNK AT 0B28 SIZE 000000BB BYTES

		call	SilenceFMChn
		jp	cfF2_StopTrk
; End of function cfE3_SilenceTrk


; =============== S U B	R O U T	I N E =======================================


cfE4_PanAnim:				; DATA XREF: RAM:cfPtrTableo
		push	ix
		pop	hl
		ld	bc, 11h
		add	hl, bc
		ex	de, hl
		ld	bc, 5
		ldir
		ld	a, 1
		ld	(de), a
		ex	de, hl
		dec	de
		ret
; End of function cfE4_PanAnim


; =============== S U B	R O U T	I N E =======================================


cfE5_ChgPFMVol:				; DATA XREF: RAM:cfPtrTableo

; FUNCTION CHUNK AT 0F3D SIZE 00000001 BYTES

		inc	de
		add	a, (ix+6)
		ld	(ix+6),	a
		ld	a, (de)

cfE6_ChgFMVol:				; DATA XREF: RAM:cfPtrTableo
		bit	7, (ix+1)
		ret	nz
		add	a, (ix+6)
		ld	(ix+6),	a
		bit	3, (ix+1)
		jp	nz, locret_F3D
; End of function cfE5_ChgPFMVol


; =============== S U B	R O U T	I N E =======================================


RefreshVolume:				; CODE XREF: SendFMIns+1Cj
					; DoFading+3Bp
		push	de
		ld	de, Volume_Ops
		ld	l, (ix+1Ch)
		ld	h, (ix+1Dh)
		ld	b, 4

loc_A5C:				; CODE XREF: RefreshVolume+2Bj
		ld	a, (hl)
		or	a
		jp	p, loc_A74
		add	a, (ix+6)
		jp	m, loc_A69
		ld	a, 0FFh

loc_A69:				; CODE XREF: RefreshVolume+14j
		push	hl
		ld	hl, byte_1C06
		add	a, (hl)		; add Fade volume
		jp	m, loc_A73
		ld	a, 0FFh

loc_A73:				; CODE XREF: RefreshVolume+1Ej
		pop	hl

loc_A74:				; CODE XREF: RefreshVolume+Ej
		and	7Fh
		ld	c, a
		ld	a, (de)
		rst	WriteFMIorII
		inc	de
		inc	hl
		djnz	loc_A5C
		pop	de
		ret
; End of function RefreshVolume


; =============== S U B	R O U T	I N E =======================================


cfE7_Hold:				; DATA XREF: RAM:cfPtrTableo
		set	1, (ix+0)
		dec	de
		ret
; End of function cfE7_Hold


; =============== S U B	R O U T	I N E =======================================


cfE8_NoteStop:				; DATA XREF: RAM:cfPtrTableo
		call	TickMultiplier	; multiply with	tempo divider
		ld	(ix+1Eh), a
		ld	(ix+1Fh), a
		ret
; End of function cfE8_NoteStop


; =============== S U B	R O U T	I N E =======================================


cfEB_LoopExit:				; DATA XREF: RAM:cfPtrTableo

; FUNCTION CHUNK AT 0C0F SIZE 00000006 BYTES

		inc	de
		add	a, 28h
		ld	c, a
		ld	b, 0
		push	ix
		pop	hl
		add	hl, bc
		ld	a, (hl)
		dec	a
		jp	z, loc_AA0
		inc	de
		ret
; ---------------------------------------------------------------------------

loc_AA0:				; CODE XREF: cfEB_LoopExit+Cj
		xor	a
		ld	(hl), a
		jp	cfF6_GoTo
; End of function cfEB_LoopExit


; =============== S U B	R O U T	I N E =======================================


cfEC_ChgPSGVol:				; DATA XREF: RAM:cfPtrTableo
		bit	7, (ix+1)
		ret	z
		res	4, (ix+0)
		dec	(ix+17h)
		add	a, (ix+6)
		cp	0Fh
		jp	c, loc_ABB
		ld	a, 0Fh		; limit	to 0F

loc_ABB:				; CODE XREF: cfEC_ChgPSGVol+11j
		ld	(ix+6),	a
		ret
; End of function cfEC_ChgPSGVol


; =============== S U B	R O U T	I N E =======================================


cfED_FMChnWrite:			; DATA XREF: RAM:cfPtrTableo
		call	ReadFMCommand
		rst	WriteFMIorII
		ret
; End of function cfED_FMChnWrite


; =============== S U B	R O U T	I N E =======================================


cfEE_FM1Write:				; DATA XREF: RAM:cfPtrTableo
		call	ReadFMCommand
		call	WriteFMI
		ret
; End of function cfEE_FM1Write


; =============== S U B	R O U T	I N E =======================================


ReadFMCommand:				; CODE XREF: cfED_FMChnWritep
					; cfEE_FM1Writep
		ex	de, hl
		ld	a, (hl)		; read Register
		inc	hl
		ld	c, (hl)		; read Data
		ex	de, hl
		ret
; End of function ReadFMCommand


; =============== S U B	R O U T	I N E =======================================


cfEF_SetFMIns:				; DATA XREF: RAM:cfPtrTableo

; FUNCTION CHUNK AT 0B0A SIZE 00000004 BYTES

		bit	7, (ix+1)
		jr	nz, loc_B0A
		call	SetMaxRelRate
		ld	a, (de)
		ld	(ix+8),	a
		or	a
		jp	p, loc_B00
		inc	de
		ld	a, (de)
		ld	(ix+0Fh), a
; End of function cfEF_SetFMIns


; =============== S U B	R O U T	I N E =======================================


SetInsFromSong:				; CODE XREF: cfE3_SilenceTrk+162p
		push	de
		ld	a, (ix+0Fh)
		sub	81h
		ld	hl, (MusListPtr)
		rst	ReadPtrTable
		ld	a, (hl)
		inc	hl
		ld	h, (hl)
		ld	l, a
		ld	a, (ix+8)
		and	7Fh
		ld	b, a
		call	JumpToInsData
		jr	loc_B05
; ---------------------------------------------------------------------------

loc_B00:				; CODE XREF: cfEF_SetFMIns+Ej
		push	de
		ld	b, a
		call	GetFMInsPtr

loc_B05:				; CODE XREF: SetInsFromSong+17j
		call	SendFMIns
		pop	de
		ret
; End of function SetInsFromSong

; ---------------------------------------------------------------------------
; START	OF FUNCTION CHUNK FOR cfEF_SetFMIns

loc_B0A:				; CODE XREF: cfEF_SetFMIns+4j
		or	a
		ret	p
		inc	de
		ret
; END OF FUNCTION CHUNK	FOR cfEF_SetFMIns

; =============== S U B	R O U T	I N E =======================================


cfF0_ModSetup:				; DATA XREF: RAM:cfPtrTableo
		ld	(ix+20h), e
		ld	(ix+21h), d
		ld	(ix+7),	80h
		inc	de
		inc	de
		inc	de
		ret
; End of function cfF0_ModSetup


; =============== S U B	R O U T	I N E =======================================


cfF1_ModTypePFM:			; DATA XREF: RAM:cfPtrTableo
		inc	de
		bit	7, (ix+1)
		jr	nz, cfF4_ModType
		ld	a, (de)

cfF4_ModType:				; CODE XREF: cfF1_ModTypePFM+5j
					; DATA XREF: RAM:cfPtrTableo
		ld	(ix+7),	a
		ret
; End of function cfF1_ModTypePFM

; ---------------------------------------------------------------------------
; START	OF FUNCTION CHUNK FOR cfE3_SilenceTrk

cfF2_StopTrk:				; CODE XREF: cfE3_SilenceTrk+3j
					; DATA XREF: RAM:cfPtrTableo
		res	7, (ix+0)
		ld	a, 1Fh
		ld	(byte_1C15), a
		ld	a, (byte_1C3D)
		or	a
		jp	m, loc_BCB
		call	DoNoteOff
		ld	c, (ix+1)
		push	ix
		call	GetSFXChnPtrs
		ld	a, (byte_1C19)
		or	a
		jp	z, loc_BC6
		xor	a
		ld	(byte_1C18), a
		push	hl
		ld	hl, (word_1C37)
		pop	ix
		res	2, (ix+0)
		bit	7, (ix+1)
		jr	nz, loc_BD1
		bit	7, (ix+0)
		jr	z, loc_BC6
		ld	a, 2
		cp	(ix+1)
		jr	nz, loc_B78
		ld	a, 4Fh
		bit	0, (ix+0)
		jr	nz, loc_B75
		and	0Fh

loc_B75:				; CODE XREF: cfE3_SilenceTrk+154j
		call	SendFM3SpcMode

loc_B78:				; CODE XREF: cfE3_SilenceTrk+14Cj
		ld	a, (ix+8)
		or	a
		jp	p, loc_B84
		call	SetInsFromSong
		jr	loc_BC3
; ---------------------------------------------------------------------------

loc_B84:				; CODE XREF: cfE3_SilenceTrk+15Fj
		ld	b, a
		push	hl
		ld	hl, byte_1C04
		ld	a, (hl)
		ld	hl, 6000h	; switch to Song Bank
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		xor	a
		ld	(hl), a
		ld	(hl), a
		ld	(hl), 1
		pop	hl
		call	JumpToInsData
		call	SendFMIns
		push	hl
		ld	hl, 6000h	; switch to SFX	Bank (8D0000)
		xor	a		; Bank bits written: 11Ah
		ld	e, 1
		ld	(hl), a
		ld	(hl), e
		ld	(hl), a
		ld	(hl), e
		ld	(hl), e
		ld	(hl), a
		ld	(hl), a
		ld	(hl), a
		ld	(hl), 1
		pop	hl
		ld	a, (ix+18h)
		or	a
		jp	p, loc_BC6
		ld	e, (ix+19h)
		ld	d, (ix+1Ah)

loc_BC3:				; CODE XREF: cfE3_SilenceTrk+165j
		call	SendSSGEG

loc_BC6:				; CODE XREF: cfE3_SilenceTrk+12Aj
					; cfE3_SilenceTrk+145j	...
		pop	ix
		pop	hl
		pop	hl
		ret
; ---------------------------------------------------------------------------

loc_BCB:				; CODE XREF: cfE3_SilenceTrk+118j
		xor	a
		ld	(byte_1C3D), a
		pop	hl
		ret
; ---------------------------------------------------------------------------

loc_BD1:				; CODE XREF: cfE3_SilenceTrk+13Fj
		bit	0, (ix+0)
		jr	z, loc_BC6
		ld	a, (ix+1Ah)
		or	a
		jp	p, loc_BE1
		ld	(PSGState_Ch4),	a

loc_BE1:				; CODE XREF: cfE3_SilenceTrk+1BEj
		jr	loc_BC6
; END OF FUNCTION CHUNK	FOR cfE3_SilenceTrk

; =============== S U B	R O U T	I N E =======================================


cfF3_PSGNoise:				; DATA XREF: RAM:cfPtrTableo
		bit	2, (ix+1)
		ret	nz
		ld	a, 0DFh
		ld	(PSGState_Ch3+2), a
		ld	a, (de)
		ld	(ix+1Ah), a
		set	0, (ix+0)
		or	a
		jr	nz, loc_C02
		res	0, (ix+0)
		ld	a, 0FFh
		ld	(PSGState_Ch4+2), a
		ret
; ---------------------------------------------------------------------------

loc_C02:				; CODE XREF: cfF3_PSGNoise+13j
		ld	(PSGState_Ch4),	a
		ret
; End of function cfF3_PSGNoise


; =============== S U B	R O U T	I N E =======================================


cfF5_SetPSGIns:				; DATA XREF: RAM:cfPtrTableo
		bit	7, (ix+1)
		ret	z
		ld	(ix+8),	a
		ret
; End of function cfF5_SetPSGIns

; ---------------------------------------------------------------------------
; START	OF FUNCTION CHUNK FOR cfEB_LoopExit

cfF6_GoTo:				; CODE XREF: cfEB_LoopExit+13j
					; cfF7_Loop+12j
					; DATA XREF: ...
		ex	de, hl
		ld	e, (hl)
		inc	hl
		ld	d, (hl)
		dec	de
		ret
; END OF FUNCTION CHUNK	FOR cfEB_LoopExit

; =============== S U B	R O U T	I N E =======================================


cfF7_Loop:				; DATA XREF: RAM:cfPtrTableo
		inc	de
		add	a, 28h
		ld	c, a
		ld	b, 0
		push	ix
		pop	hl
		add	hl, bc
		ld	a, (hl)
		or	a
		jr	nz, loc_C25
		ld	a, (de)
		ld	(hl), a

loc_C25:				; CODE XREF: cfF7_Loop+Cj
		inc	de
		dec	(hl)
		jp	nz, cfF6_GoTo
		inc	de
		ret
; End of function cfF7_Loop


; =============== S U B	R O U T	I N E =======================================


cfF8_GoSub:				; DATA XREF: RAM:cfPtrTableo
		ld	c, a
		inc	de
		ld	a, (de)
		ld	b, a
		push	bc
		push	ix
		pop	hl
		dec	(ix+9)
		ld	c, (ix+9)
		dec	(ix+9)
		ld	b, 0
		add	hl, bc
		ld	(hl), d
		dec	hl
		ld	(hl), e
		pop	de
		dec	de
		ret
; End of function cfF8_GoSub


; =============== S U B	R O U T	I N E =======================================


cfF9_Return:				; DATA XREF: RAM:cfPtrTableo
		push	ix
		pop	hl
		ld	c, (ix+9)
		ld	b, 0
		add	hl, bc
		ld	e, (hl)
		inc	hl
		ld	d, (hl)
		inc	(ix+9)
		inc	(ix+9)
		ret
; End of function cfF9_Return


; =============== S U B	R O U T	I N E =======================================


cfFA_TickMult:				; DATA XREF: RAM:cfPtrTableo
		ld	(ix+2),	a
		ret
; End of function cfFA_TickMult


; =============== S U B	R O U T	I N E =======================================


cfFB_ChgTransp:				; DATA XREF: RAM:cfPtrTableo
		add	a, (ix+5)
		ld	(ix+5),	a
		ret
; End of function cfFB_ChgTransp


; =============== S U B	R O U T	I N E =======================================


cfFC_PitchSlide:			; DATA XREF: RAM:cfPtrTableo
		cp	1
		jr	nz, loc_C6D
		set	5, (ix+0)
		ret
; ---------------------------------------------------------------------------

loc_C6D:				; CODE XREF: cfFC_PitchSlide+2j
		res	1, (ix+0)
		res	5, (ix+0)
		xor	a
		ld	(ix+10h), a
		ret
; End of function cfFC_PitchSlide


; =============== S U B	R O U T	I N E =======================================


cfFD_RawFrqMode:			; DATA XREF: RAM:cfPtrTableo
		cp	1
		jr	nz, loc_C83
		set	3, (ix+0)
		ret
; ---------------------------------------------------------------------------

loc_C83:				; CODE XREF: cfFD_RawFrqMode+2j
		res	3, (ix+0)
		ret
; End of function cfFD_RawFrqMode


; =============== S U B	R O U T	I N E =======================================


cfFE_SpcFM3Mode:			; DATA XREF: RAM:cfPtrTableo

; FUNCTION CHUNK AT 0CBB SIZE 00000004 BYTES

		ld	a, (ix+1)
		cp	2
		jr	nz, SpcFM3_skip
		set	0, (ix+0)
		ex	de, hl
		call	GetFM3FreqPtr
		ld	b, 4

loc_C99:				; CODE XREF: cfFE_SpcFM3Mode+23j
		push	bc
		ld	a, (hl)
		inc	hl
		push	hl
		ld	hl, FM3_FreqVals
		add	a, a
		ld	c, a
		ld	b, 0
		add	hl, bc
		ldi
		ldi
		pop	hl
		pop	bc
		djnz	loc_C99
		ex	de, hl
		dec	de
		ld	a, 4Fh
; End of function cfFE_SpcFM3Mode


; =============== S U B	R O U T	I N E =======================================


SendFM3SpcMode:				; CODE XREF: cfE3_SilenceTrk:loc_B75p
		ld	(byte_1C12), a
		ld	c, a
		ld	a, 27h
		call	WriteFMI
		ret
; End of function SendFM3SpcMode

; ---------------------------------------------------------------------------
; START	OF FUNCTION CHUNK FOR cfFE_SpcFM3Mode

SpcFM3_skip:				; CODE XREF: cfFE_SpcFM3Mode+5j
		inc	de
		inc	de
		inc	de
		ret
; END OF FUNCTION CHUNK	FOR cfFE_SpcFM3Mode
; ---------------------------------------------------------------------------
FM3_FreqVals:	dw 0, 132h, 18Eh, 1E4h,	234h, 27Eh, 2C2h, 2F0h
					; DATA XREF: cfFE_SpcFM3Mode+15o

; =============== S U B	R O U T	I N E =======================================


cfMetaCoordFlag:			; DATA XREF: RAM:cfPtrTableo
		ld	hl, cfMetaPtrTable
		rst	ReadPtrTable
		inc	de
		ld	a, (de)
		jp	(hl)
; End of function cfMetaCoordFlag


; =============== S U B	R O U T	I N E =======================================


cf00_SetTempo:				; DATA XREF: RAM:cfMetaPtrTableo
		ld	(byte_1C14), a
		ld	(byte_1C13), a
		ret
; End of function cf00_SetTempo


; =============== S U B	R O U T	I N E =======================================


cf01_PlaySnd:				; DATA XREF: RAM:cfMetaPtrTableo
		ld	(byte_1C09), a	; put into Sound Queue
		ret
; End of function cf01_PlaySnd


; =============== S U B	R O U T	I N E =======================================


cf02_MusPause:				; DATA XREF: RAM:cfMetaPtrTableo
		ld	(byte_1C11), a	; 1C11 - Music is paused
		or	a
		jr	z, loc_D04	; 00 - unpause,	so jump
		push	ix		; 01-FF	- pause	music
		push	de
		ld	ix, byte_1C40
		ld	b, 0Dh
		ld	de, 30h

loc_CF3:				; CODE XREF: cf02_MusPause+1Bj
		res	7, (ix+0)
		call	SendNoteOff
		add	ix, de
		djnz	loc_CF3
		pop	de
		pop	ix
		jp	PSGSilenceAll
; ---------------------------------------------------------------------------

loc_D04:				; CODE XREF: cf02_MusPause+4j
		push	ix		; resume music
		push	de
		ld	ix, byte_1C40
		ld	b, 0Dh
		ld	de, 30h

loc_D10:				; CODE XREF: cf02_MusPause+35j
		set	7, (ix+0)
		add	ix, de
		djnz	loc_D10
		pop	de
		pop	ix
		ret
; End of function cf02_MusPause


; =============== S U B	R O U T	I N E =======================================


cf03_CopyMem:				; DATA XREF: RAM:cfMetaPtrTableo
		ex	de, hl
		ld	e, (hl)
		inc	hl
		ld	d, (hl)
		inc	hl
		ld	c, (hl)
		ld	b, 0
		inc	hl
		ex	de, hl
		ldir
		dec	de
		ret
; End of function cf03_CopyMem


; =============== S U B	R O U T	I N E =======================================


cf04_TickMulAll:			; DATA XREF: RAM:cfMetaPtrTableo
		ld	b, 0Dh
		ld	hl,  byte_1C40+2

loc_D2F:				; CODE XREF: cf04_TickMulAll+Cj
		push	bc
		ld	bc, 30h
		ld	(hl), a
		add	hl, bc
		pop	bc
		djnz	loc_D2F
		ret
; End of function cf04_TickMulAll


; =============== S U B	R O U T	I N E =======================================


cf05_SSGEG:				; DATA XREF: RAM:cfMetaPtrTableo
		ld	(ix+18h), 80h
		ld	(ix+19h), e
		ld	(ix+1Ah), d
; End of function cf05_SSGEG


; =============== S U B	R O U T	I N E =======================================


SendSSGEG:				; CODE XREF: cfE3_SilenceTrk:loc_BC3p
		ld	hl, SSGEG_Regs
		ld	b, 4

loc_D48:				; CODE XREF: SendSSGEG+Bj
		ld	a, (de)
		inc	de
		ld	c, a
		ld	a, (hl)
		inc	hl
		rst	WriteFMIorII
		djnz	loc_D48
		dec	de
		ret
; End of function SendSSGEG


; =============== S U B	R O U T	I N E =======================================


cf06_FMVolEnv:				; DATA XREF: RAM:cfMetaPtrTableo
		ld	(ix+18h), a
		inc	de
		ld	a, (de)
		ld	(ix+19h), a
		ret
; End of function cf06_FMVolEnv

; ---------------------------------------------------------------------------
; START	OF FUNCTION CHUNK FOR UpdateTrack

UpdatePSGTrk:				; CODE XREF: UpdateTrack+4j
		call	TrackTimeout
		jr	nz, loc_D6D
		call	TrkUpdate_Proc
		bit	4, (ix+0)
		ret	nz
		call	PrepareModulat
		jr	loc_D79
; ---------------------------------------------------------------------------

loc_D6D:				; CODE XREF: UpdateTrack+C50j
		ld	a, (ix+1Eh)
		or	a
		jr	z, loc_D79
		dec	(ix+1Eh)
		jp	z, SetRest

loc_D79:				; CODE XREF: UpdateTrack+C5Dj
					; UpdateTrack+C63j
		call	DoPitchSlide
		call	DoModulation
		bit	2, (ix+0)
		ret	nz
		ld	c, (ix+1)
		ld	a, l
		and	0Fh
		or	c
		exx
		push	af
		ld	a, (ix+1)
		sub	80h
		srl	a
		srl	a
		srl	a
		ld	b, 0
		ld	c, a
		ld	hl, PSGState_Ch1
		add	hl, bc
		pop	af
		ld	(hl), a
		inc	hl
		exx
		ld	a, l
		and	0F0h
		or	h
		rrca
		rrca
		rrca
		rrca
		exx
		ld	(hl), a
		exx
		ld	a, (ix+8)
		or	a
		ld	c, 0
		jr	z, loc_DBF
		dec	a
		ld	hl, (VolEnvListPtr)
		rst	ReadPtrTable
		call	DoPSGVolEnv
		ld	c, a

loc_DBF:				; CODE XREF: UpdateTrack+CA6j
		bit	4, (ix+0)
		ret	nz
		ld	a, (ix+6)
		add	a, c
		bit	4, a
		jr	z, loc_DCE
		ld	a, 0Fh

loc_DCE:				; CODE XREF: UpdateTrack+CBCj
		or	(ix+1)
		add	a, 10h
		bit	0, (ix+0)
		jr	nz, loc_DEF
		push	af
		ld	a, (ix+1)
		sub	80h
		srl	a
		srl	a
		srl	a
		ld	b, 0
		ld	c, a
		ld	hl,  PSGState_Ch1+2
		add	hl, bc
		pop	af
		ld	(hl), a
		ret
; ---------------------------------------------------------------------------

loc_DEF:				; CODE XREF: UpdateTrack+CC9j
		or	0F0h
		ld	(PSGState_Ch4+2), a
		ret
; END OF FUNCTION CHUNK	FOR UpdateTrack
; ---------------------------------------------------------------------------
; START	OF FUNCTION CHUNK FOR DoPSGVolEnv

loc_DF5:				; CODE XREF: DoPSGVolEnv+1Bj
					; DoPSGVolEnv+26j
		ld	(ix+17h), a
; END OF FUNCTION CHUNK	FOR DoPSGVolEnv

; =============== S U B	R O U T	I N E =======================================


DoPSGVolEnv:				; CODE XREF: DoFMVolEnv+Bp
					; UpdateTrack+CADp

; FUNCTION CHUNK AT 0DF5 SIZE 00000003 BYTES

		push	hl
		ld	c, (ix+17h)
		ld	b, 0
		add	hl, bc
		ld	a, (hl)
		pop	hl
		bit	7, a
		jr	z, VolEnv_Next
		cp	83h
		jr	z, VolEnv_Off	; 83 - stop the	tone
		cp	81h
		jr	z, VolEnv_Hold	; 81 - hold the	envelope at current level
		cp	80h
		jr	z, VolEnv_Reset	; 80 - loop back to beginning
		inc	bc		; 82 xx	- loop back to index xx
		ld	a, (bc)
		jr	loc_DF5
; ---------------------------------------------------------------------------

VolEnv_Off:				; CODE XREF: DoPSGVolEnv+Fj
		set	4, (ix+0)
		pop	hl
		jp	SetRest
; ---------------------------------------------------------------------------

VolEnv_Reset:				; CODE XREF: DoPSGVolEnv+17j
		xor	a
		jr	loc_DF5
; ---------------------------------------------------------------------------

VolEnv_Hold:				; CODE XREF: DoPSGVolEnv+13j
		pop	hl
		set	4, (ix+0)
		ret
; ---------------------------------------------------------------------------

VolEnv_Next:				; CODE XREF: DoPSGVolEnv+Bj
		inc	(ix+17h)
		ret
; End of function DoPSGVolEnv


; =============== S U B	R O U T	I N E =======================================


SetRest:				; CODE XREF: TrkUpdate_Proc+2Dp
					; UpdateTrack+C68j ...
		set	4, (ix+0)
		bit	2, (ix+0)
		ret	nz
; End of function SetRest


; =============== S U B	R O U T	I N E =======================================


SilencePSGChn:				; CODE XREF: GetSFXChnPtrs+Fp
		ld	a, (ix+1)
		or	a
		ret	p
		sub	80h
		srl	a
		srl	a
		srl	a
		ld	b, 0
		ld	c, a
		ld	hl,  PSGState_Ch1+2
		add	hl, bc
		ld	a, 1Fh
		add	a, (ix+1)
		ld	(hl), a
		bit	0, (ix+0)
		ret	z
		ld	a, 0FFh
		ld	(PSGState_Ch4+2), a
		ret
; End of function SilencePSGChn


; =============== S U B	R O U T	I N E =======================================


SendPSGState:				; CODE XREF: RAM:006Ap	UpdateAll+37p ...
		ld	hl, 6000h	; switch to Bank 400000
		xor	a		; Bank bits written: 080h
		ld	b, 7

loc_E5E:				; CODE XREF: SendPSGState+7j
		ld	(hl), a
		djnz	loc_E5E
		ld	(hl), 1
		ld	(hl), a		; This should probably be 1. (so that it switches to C00000, the 68k VDP spcae)
		ld	hl, PSGState_Ch1
		ld	b, 3		; 3 PSG	channels with frequency	+ volume

loc_E69:				; CODE XREF: SendPSGState:loc_E80j
		ld	a, (hl)		; load frequency into AC
		inc	hl
		ld	c, (hl)
		inc	hl
		or	a
		jr	z, loc_E77
		ld	(7F11h), a	; if non-null, send to PSG chip
		ld	a, c
		ld	(7F11h), a

loc_E77:				; CODE XREF: SendPSGState+16j
		ld	a, (hl)		; get Volume
		inc	hl
		inc	hl		; skip unused byte
		or	a
		jr	z, loc_E80
		ld	(7F11h), a	; if non-null, send to PSG chip

loc_E80:				; CODE XREF: SendPSGState+23j
		djnz	loc_E69
		ld	a, (hl)		; get Noise frequency
		inc	hl
		inc	hl
		or	a
		jr	z, loc_E8B
		ld	(7F11h), a	; if non-null, send to PSG chip

loc_E8B:				; CODE XREF: SendPSGState+2Ej
		ld	a, (hl)
		or	a
		jr	z, loc_E92
		ld	(7F11h), a	; send PSG Noise volume

loc_E92:				; CODE XREF: SendPSGState+35j
		ld	hl, PSGState_Ch1
		ld	de,  PSGState_Ch1+1
		ld	bc, 0Fh
		ld	(hl), 0
		ldir			; clear	PSG state
		ld	hl, byte_1C04
		ld	a, (hl)
		ld	hl, 6000h	; switch to Song Bank
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		xor	a
		ld	(hl), a
		ld	(hl), a
		ld	(hl), 1
		ret
; End of function SendPSGState

; ---------------------------------------------------------------------------
PSGState_Ch1:	db 0, 0, 0, 0		; DATA XREF: RAM:loc_6Eo
					; UpdateTrack+C8Do ...
PSGState_Ch2:	db 0, 0, 0, 0
PSGState_Ch3:	db 0, 0, 0, 0		; DATA XREF: cfF3_PSGNoise+7w
PSGState_Ch4:	db 0, 0, 0, 0		; DATA XREF: cfE3_SilenceTrk+1C1w
					; cfF3_PSGNoise:loc_C02w ...
; ---------------------------------------------------------------------------
; START	OF FUNCTION CHUNK FOR UpdateTrack

UpdatePWMTrk:				; CODE XREF: UpdateTrack+Bj
		call	TrackTimeout
		ret	nz
		ld	a, 80h
		ld	(byte_1C3D), a	; set "processing PWM track" status byte
		ld	e, (ix+3)
		ld	d, (ix+4)
		res	1, (ix+0)

loc_EDA:				; CODE XREF: RAM:0F30j
		ld	a, (de)
		inc	de
		ld	hl, cfReturn_PWM
		cp	0E0h
		jp	nc, cfHandler_JmpIn
		or	a
		jp	p, SetDuration_PWM ; 00-7F - Delay
		ld	(ix+0Dh), a	; save Drum sound
		ld	a, (de)		; read next byte
		or	a
		jp	p, loc_F33	; is a delay - jump and	read it
		ld	a, (ix+0Ch)	; else re-use the last delay
		ld	(ix+0Bh), a

loc_EF6:				; CODE XREF: UpdateTrack+E2Cj
		ld	hl, unk_1BF8	; 1BF8 - PWM Sound Commands
		ld	a, (ix+1)	; get Channel Bits
		sub	18h		; PWM bits 18/1A/1C/1E -> 00/02/04/06
		ld	c, a
		ld	b, 0
		add	hl, bc		; HL = 1BF8 + (ChnBits - 18)
		ld	a, (ix+0Dh)
		cp	80h		; is this sound	80?
		jp	z, loc_F0E	; yes -	skip
		ld	a, (ix+6)
		ld	(hl), a		; write	Volume/Pan

loc_F0E:				; CODE XREF: UpdateTrack+DF9j
		inc	hl
		bit	1, (ix+0)	; "hold note" bit set?
		jr	nz, loc_F1E	; yes -	skip (prevents sound from restarting)
		ld	a, (ix+0Dh)
		sub	81h		; SMPS note 81 is Sample ID 00
		jp	m, loc_F1E	; skip invalid IDs
		ld	(hl), a

loc_F1E:				; CODE XREF: UpdateTrack+E05j
					; UpdateTrack+E0Cj
		ld	(ix+3),	e
		ld	(ix+4),	d
		ld	a, (ix+0Ch)
		ld	(ix+0Bh), a
		xor	a
		ld	(byte_1C3D), a
		ret
; END OF FUNCTION CHUNK	FOR UpdateTrack
; ---------------------------------------------------------------------------

cfReturn_PWM:				; DATA XREF: UpdateTrack+DCEo
		inc	de
		jp	loc_EDA
; ---------------------------------------------------------------------------
; START	OF FUNCTION CHUNK FOR UpdateTrack

loc_F33:				; CODE XREF: UpdateTrack+DDFj
		inc	de

SetDuration_PWM:			; CODE XREF: UpdateTrack+DD7j
		call	TickMultiplier
		ld	(ix+0Ch), a
		jp	loc_EF6
; END OF FUNCTION CHUNK	FOR UpdateTrack
; ---------------------------------------------------------------------------
; START	OF FUNCTION CHUNK FOR cfE5_ChgPFMVol

locret_F3D:				; CODE XREF: cfE5_ChgPFMVol+17j
		ret
; END OF FUNCTION CHUNK	FOR cfE5_ChgPFMVol

; =============== S U B	R O U T	I N E =======================================


SetReadyStatus:				; CODE XREF: UpdateAll+3Ap
		ld	hl, byte_1BF7	; 1BF7 - Status	Byte
		dec	(hl)		; set to FF (finished)
		ret
; End of function SetReadyStatus

; ---------------------------------------------------------------------------
Garbage_0F43:	db 0, 17h, 11h,	8Dh, 10h, 3Bh, 10h, 8Dh, 10h, 86h, 12h
		db 5Ah,	11h, 2Ah, 0, 0,	0, 12h,	10h, 18h, 18h, 18h, 18h
		db 18h,	18h, 18h, 18h, 18h, 18h, 18h, 18h, 18h,	18h, 19h
		db 19h,	19h, 19h, 19h, 19h, 19h, 19h, 19h, 19h,	19h, 19h
		db 19h,	19h, 19h, 19h, 19h, 19h, 19h, 19h, 19h,	19h, 19h
		db 1Ah,	1Ah, 1Ah, 1Ah, 0, 80h, 61h, 8Dh, 4, 99h, 0A6h
		db 0A8h, 9Ah, 0B4h, 20h, 0C2h, 9Ch, 0D0h, 6Bh, 0D3h, 0EEh
		db 0DDh, 0BEh, 0E1h, 0E5h, 0E8h, 0E8h, 0EFh, 0E3h, 0F4h
		db 0F0h, 0F7h, 0, 80h, 6Ah, 83h, 39h, 8Ah, 96h,	8Ch, 5Dh
		db 91h,	1Dh, 95h, 0B0h,	9Fh, 8Ch, 0A5h,	3Ch, 0ACh, 82h
		db 0B0h, 0F5h, 0B6h, 0FFh, 0BBh, 4Eh, 0C4h, 0FAh, 0C8h
		db 0Dh,	0CDh, 0EFh, 0D0h, 4Ch, 0D3h, 3Fh, 0D5h,	7Ah, 0D6h
		db 1Dh,	0D8h, 0F4h, 0D9h, 41h, 0DCh, 3Dh, 0E3h,	0, 80h
		db 0ACh, 89h, 6Ah, 8Ch,	0Bh, 0C0h, 0, 0E0h, 28h, 0E0h
		db 5Bh,	0E0h, 9Ch, 0E0h, 0CAh, 0E0h, 1Bh, 0E1h,	74h, 0E1h
		db 9Eh,	0E1h, 1, 0E2h, 39h, 0E2h, 0B3h,	0E2h, 0DFh, 0E2h
		db 17h,	0E3h, 56h, 0E3h, 8Dh, 0E3h, 0AAh, 0E3h,	0CAh, 0E3h
		db 25h,	0E4h, 7Eh, 0E4h, 0BFh, 0E4h, 0F8h, 0E4h, 31h, 0E5h
		db 6Bh,	0E5h, 0A0h
SndPrioPtr:	dw SndPriorities	; DATA XREF: DoSoundQueue+16r
		dw SFXPtrs		; actually SpcSFXPtrs
MusListPtr:	dw MusicPtrs		; DATA XREF: PlaySoundID+6Fr
					; SetInsFromSong+6r
SFXListPtr:	dw SFXPtrs		; DATA XREF: PlaySoundID+155r
ModEnvListPtr:	dw ModEnvPtrs		; DATA XREF: DoModulation+53r
VolEnvListPtr:	dw VolEnvPtrs		; DATA XREF: DoFMVolEnv+7r
					; UpdateTrack+CA9r
		dw 2Ah
		dw 0
SongBankPtr:	dw SongBanks		; DATA XREF: PlaySoundID+4Br
SongBanks:	db 18h,	18h, 18h, 18h, 18h, 18h, 18h, 18h ; DATA XREF: RAM:SongBankPtro
		db 18h,	18h, 18h, 18h, 18h, 18h, 19h, 19h
		db 19h,	19h, 19h, 19h, 19h, 19h, 19h, 19h
		db 19h,	19h, 19h, 19h, 19h, 19h, 19h, 19h
		db 19h,	19h, 19h, 19h, 19h, 1Ah, 1Ah, 1Ah
		db 1Ah
MusicPtrs:	dw   8000h,  8D61h,  9904h, 0A8A6h, 0B49Ah, 0C220h, 0D09Ch, 0D36Bh
					; DATA XREF: RAM:MusListPtro
		dw  0DDEEh, 0E1BEh, 0E8E5h, 0EFE8h, 0F4E3h, 0F7F0h,  8000h,  836Ah
		dw   8A39h,  8C96h,  915Dh,  951Dh,  9FB0h, 0A58Ch, 0AC3Ch, 0B082h
		dw  0B6F5h, 0BBFFh, 0C44Eh, 0C8FAh, 0CD0Dh, 0D0EFh, 0D34Ch, 0D53Fh
		dw  0D67Ah, 0D81Dh, 0D9F4h, 0DC41h, 0E33Dh,  8000h,  89ACh,  8C6Ah
		dw  0C00Bh
SFXPtrs:	dw  0E000h, 0E028h, 0E05Bh, 0E09Ch, 0E0CAh, 0E11Bh, 0E174h, 0E19Eh
					; DATA XREF: RAM:1002o	RAM:SFXListPtro
		dw  0E201h, 0E239h, 0E2B3h, 0E2DFh, 0E317h, 0E356h, 0E38Dh, 0E3AAh
		dw  0E3CAh, 0E425h, 0E47Eh, 0E4BFh, 0E4F8h, 0E531h, 0E56Bh, 0E5A0h
		dw  0E603h, 0E65Ah, 0E68Bh, 0E6B5h, 0E6DFh, 0E754h, 0E79Ch, 0E7FDh
		dw  0E82Dh, 0E83Ah, 0E880h, 0E8ADh, 0E8F0h, 0E926h, 0E983h, 0E9B1h
		dw  0E9DFh, 0EA22h, 0EA40h, 0EA6Dh, 0EAA8h, 0EAD0h, 0EB0Eh, 0EB40h
		dw  0EB78h, 0EBB0h, 0EBF6h, 0EC44h, 0EC6Eh, 0EC97h, 0ECCAh, 0ED45h
		dw  0ED79h, 0EDA6h, 0EDD8h, 0EE18h, 0EE45h, 0EE7Bh, 0EEA8h, 0EEEBh
		dw  0EF00h, 0EF11h, 0F010h, 0F04Eh, 0F07Bh
SndPriorities:	db 7Fh,	7Fh, 7Fh, 7Fh, 7Fh, 7Fh, 7Fh, 7Fh, 7Fh,	7Fh, 7Fh
					; DATA XREF: RAM:SndPrioPtro
		db 7Fh,	7Fh, 7Fh, 7Fh, 7Fh, 7Fh, 7Fh, 7Fh, 7Fh,	7Fh, 7Fh
		db 7Fh,	7Fh, 7Fh, 7Fh, 7Fh, 7Fh, 7Fh, 7Fh, 7Fh,	7Fh, 7Fh
		db 7Fh,	7Fh, 7Fh, 7Fh, 7Fh, 7Fh, 7Fh, 7Fh, 7Fh,	7Fh, 7Fh
		db 7Fh,	7Fh, 7Fh, 7Fh, 7Fh, 7Fh, 7Fh, 7Fh, 7Fh,	7Fh, 7Fh
		db 7Fh,	7Fh, 7Fh, 7Fh, 7Fh, 7Fh, 7Fh, 7Fh, 7Fh,	7Fh, 7Fh
		db 7Fh
VolEnvPtrs:	dw byte_1176, byte_1178, byte_1181, byte_118B, byte_1197
					; DATA XREF: RAM:VolEnvListPtro
		dw byte_11A2, byte_11C9, byte_120D, byte_1215, byte_122A
		dw byte_123F, byte_1249, byte_1252, byte_127F
byte_1176:	db 2, 83h		; DATA XREF: RAM:VolEnvPtrso
byte_1178:	db 0, 0, 0, 2, 4, 6, 8,	10h, 83h ; DATA	XREF: RAM:VolEnvPtrso
byte_1181:	db 1, 0, 0, 0, 2, 4, 6,	8, 10h,	83h ; DATA XREF: RAM:VolEnvPtrso
byte_118B:	db 4, 3, 2, 1, 0, 0, 1,	1, 2, 2, 2, 81h	; DATA XREF: RAM:VolEnvPtrso
byte_1197:	db 3, 0, 1, 1, 1, 2, 3,	4, 4, 5, 81h ; DATA XREF: RAM:VolEnvPtrso
byte_11A2:	db 0, 0, 0, 0, 1, 1, 1,	1, 1, 1, 2, 2, 2, 2, 2,	2, 2, 3
					; DATA XREF: RAM:VolEnvPtrso
		db 3, 3, 3, 4, 4, 4, 4,	5, 5, 5, 6, 6, 6, 7, 8,	0Ah, 0Ch
		db 0Eh,	10h, 12h, 83h
byte_11C9:	db 12h,	12h, 11h, 11h, 10h, 10h, 0Fh, 0Fh, 0Fh,	0Eh, 0Eh
					; DATA XREF: RAM:VolEnvPtrso
		db 0Eh,	0Dh, 0Dh, 0Dh, 0Dh, 0Ch, 0Ch, 0Ch, 0Ch,	0Bh, 0Bh
		db 0Bh,	0Bh, 0Bh, 0Ah, 0Ah, 0Ah, 0Ah, 9, 9, 9, 9, 8, 8
		db 8, 8, 7, 7, 7, 7, 6,	6, 6, 6, 5, 5, 5, 5, 4,	4, 4, 4
		db 3, 3, 3, 2, 2, 2, 1,	1, 1, 0, 0, 2, 1, 0, 81h
byte_120D:	db 2, 1, 0, 0, 1, 1, 2,	81h ; DATA XREF: RAM:VolEnvPtrso
byte_1215:	db 6, 6, 6, 6, 6, 5, 5,	5, 5, 5, 4, 4, 4, 3, 3,	3, 3, 3
					; DATA XREF: RAM:VolEnvPtrso
		db 3, 2, 81h
byte_122A:	db 1, 0, 0, 0, 0, 1, 1,	1, 2, 2, 2, 3, 3, 3, 3,	4, 4, 4
					; DATA XREF: RAM:VolEnvPtrso
		db 5, 5, 81h
byte_123F:	db 10h,	20h, 30h, 40h, 30h, 20h, 10h, 0, 0F0h, 80h
					; DATA XREF: RAM:VolEnvPtrso
byte_1249:	db 0, 0, 1, 1, 3, 3, 4,	5, 83h ; DATA XREF: RAM:VolEnvPtrso
byte_1252:	db 0, 0, 0, 0, 1, 1, 1,	1, 2, 2, 2, 2, 3, 3, 3,	3, 4, 4
					; DATA XREF: RAM:VolEnvPtrso
		db 4, 4, 5, 5, 5, 5, 6,	6, 6, 6, 7, 7, 7, 7, 8,	8, 8, 8
		db 9, 9, 9, 9, 0Ah, 0Ah, 0Ah, 0Ah, 81h
byte_127F:	db 0, 0, 2, 5, 9, 0Eh, 83h ; DATA XREF:	RAM:VolEnvPtrso
ModEnvPtrs:	dw byte_129A, byte_12A6, byte_12B3, byte_12BF, byte_1301
					; DATA XREF: RAM:ModEnvListPtro
		dw byte_1336, byte_1373, byte_138D, byte_13A7, byte_13AF
byte_129A:	db 40h,	60h, 70h, 60h, 50h, 30h, 10h, 0F0h, 0D0h, 0B0h
					; DATA XREF: RAM:ModEnvPtrso
		db 90h,	83h
byte_12A6:	db 0, 2, 4, 6, 8, 0Ah, 0Ch, 0Eh, 10h, 12h, 14h,	18h, 81h
					; DATA XREF: RAM:ModEnvPtrso
byte_12B3:	db 0, 0, 1, 3, 1, 0, 0FFh, 0FDh, 0FFh, 0, 82h, 2
					; DATA XREF: RAM:ModEnvPtrso
byte_12BF:	db 0, 0, 0, 0, 0, 0, 0,	0, 0, 0, 0, 0, 0, 0, 0,	0, 0, 0
					; DATA XREF: RAM:ModEnvPtrso
		db 0, 0, 0, 0, 0, 0, 0,	0, 0, 0, 0, 0, 0, 0, 0,	0, 0, 0
		db 0, 0, 0, 0, 2, 4, 6,	8, 0Ah,	0Ch, 0Ah, 8, 6,	4, 2, 0
		db 0FEh, 0FCh, 0FAh, 0F8h, 0F6h, 0F4h, 0F6h, 0F8h, 0FAh
		db 0FCh, 0FEh, 0, 82h, 29h
byte_1301:	db 0, 0, 0, 0, 0, 0, 0,	0, 0, 0, 0, 0, 0, 0, 0,	0, 0, 0
					; DATA XREF: RAM:ModEnvPtrso
		db 0, 0, 0, 0, 0, 0, 0,	0, 0, 0, 2, 4, 6, 8, 0Ah, 0Ch
		db 0Ah,	8, 6, 4, 2, 0, 0FEh, 0FCh, 0FAh, 0F8h, 0F6h, 0F4h
		db 0F6h, 0F8h, 0FAh, 0FCh, 0FEh, 82h, 1Bh
byte_1336:	db 0, 0, 0, 0, 0, 0, 0,	0, 0, 0, 0, 0, 0, 0, 0,	0, 0, 0
					; DATA XREF: RAM:ModEnvPtrso
		db 0, 0, 0, 0, 0, 0, 0,	0, 0, 0, 0, 0, 0, 0, 0,	0, 0, 0
		db 0, 0, 0, 0, 0, 0, 0,	0, 0, 0, 0, 0, 0, 0, 3,	6, 3, 0
		db 0FDh, 0FAh, 0FAh, 0FDh, 0, 82h, 33h
byte_1373:	db 0, 0, 0, 0, 0, 0, 0,	0, 0, 0, 0, 0, 0, 0, 0,	0, 2, 4
					; DATA XREF: RAM:ModEnvPtrso
		db 2, 0, 0FEh, 0FCh, 0FEh, 0, 82h, 11h
byte_138D:	db 0FEh, 0FFh, 0, 0, 0,	0, 0, 0, 0, 0, 0, 0, 0,	0, 0, 0
					; DATA XREF: RAM:ModEnvPtrso
		db 0, 0, 1, 1, 0, 0, 0FFh, 0FFh, 82h, 11h
byte_13A7:	db 3, 2, 1, 0, 0, 0, 1,	81h ; DATA XREF: RAM:ModEnvPtrso
byte_13AF:	db 0, 0, 0, 0, 1, 1, 1,	1, 2, 2, 1, 1, 1, 0, 0,	0, 84h
					; DATA XREF: RAM:ModEnvPtrso
		db 1, 82h, 4
Garbage_13C3:	db 0, 11h, 0C0h, 0FCh, 0FCh, 33h, 0FCh,	1, 0, 0, 0A1h
		db 11h,	0, 8, 39h, 0, 0, 0, 0A1h, 11h, 0, 66h, 0F6h, 2Fh
		db 8, 41h, 0F9h, 0, 0A0h, 1Ch, 0Ah, 0Ch, 0, 0, 2Ah, 6Ch
		db 10h,	13h, 0FCh, 0, 80h, 0, 0A0h, 0, 3Fh, 10h, 0C0h
		db 10h,	0C0h, 10h, 80h,	60h, 0Eh, 4Ah, 18h, 67h, 8, 4Ah
		db 18h,	67h, 4,	4Ah, 18h, 66h, 2, 11h, 0, 20h, 5Fh, 33h
		db 0FCh, 0, 0, 0, 0A1h,	11h, 0,	4Eh, 75h, 30h, 38h, 0DFh
		db 0F2h, 0Ch, 40h, 0, 7, 64h, 0Eh, 10h,	3Bh, 0,	4, 60h
		db 0A2h, 5, 3, 7, 2, 4,	1, 11h,	0, 30h,	38h, 0DFh, 0F4h
		db 67h,	0Ch, 10h, 3Bh, 0, 3, 60h, 8Eh, 1Bh, 24h, 1Ah, 14h
		db 0F1h, 0F1h, 70h, 6, 0C0h, 78h, 0DFh,	0F6h, 0E2h, 8
		db 6, 0, 0, 9, 60h, 0, 0FFh, 7Ah, 48h, 0E7h, 0E0h, 80h
		db 33h,	0FCh, 1, 0, 0, 0A1h, 11h, 0, 8,	39h, 0,	0, 0, 0A1h
		db 11h,	0, 66h,	0F6h, 70h, 0, 72h, 0, 74h, 0, 41h, 0F9h
		db 0, 0A0h, 1Bh, 0F7h, 4Ah, 18h, 67h, 3Eh, 10h,	18h, 48h
		db 40h,	12h, 18h, 48h, 41h, 10h, 18h, 0E1h, 88h, 12h, 18h
		db 80h,	81h, 14h, 18h, 48h, 42h, 12h, 18h, 48h,	41h, 14h
		db 18h,	0E1h, 8Ah, 12h,	18h, 82h, 82h, 11h, 2, 11h, 2
		db 11h,	2, 11h,	2, 11h,	2, 11h,	2, 11h,	2, 11h,	2, 11h
		db 2, 23h, 0C0h, 0, 0A1h, 51h, 28h, 23h, 0C1h, 0, 0A1h
		db 51h,	2Ch, 33h, 0FCh,	0, 0, 0, 0A1h, 11h, 0, 4Ch, 0DFh
		db 1, 7, 4Eh, 75h, 30h,	38h, 0DFh, 0E0h, 4Eh, 0BBh, 0
		db 0Eh,	50h, 0F8h, 0FFh, 0D1h, 4Ah, 38h, 0FFh, 0D1h, 66h
		db 0FAh, 4Eh, 75h, 60h,	0, 0, 6, 60h, 0, 1, 0, 48h, 50h
		db 41h,	0FAh, 0, 0DAh, 21h, 0C8h, 0C0h,	32h, 4Ch, 0DFh
		db 1, 0, 46h, 0FCh, 27h, 0, 4Eh, 0B9h, 0, 8Fh, 42h, 98h
		db 42h,	78h, 0DFh, 0E2h, 42h, 78h, 0FBh, 0C0h, 42h, 78h
		db 0FBh, 0C2h, 42h, 78h, 0DFh, 0F0h, 42h, 78h, 0DFh, 0F2h
		db 42h,	78h, 0DFh, 0F6h, 21h, 0FCh, 1, 1, 1, 1,	0DFh, 0FEh
		db 11h,	0FCh, 0, 1, 0E0h, 2, 31h, 0FCh,	0, 2, 0E0h, 38h
		db 31h,	0FCh, 0, 0, 0E0h, 3Ah, 31h, 0FCh, 0, 1,	0DFh, 0F4h
		db 31h,	0FCh, 0FFh, 0FFh, 0E0h,	1Ch, 31h, 0FCh,	0FFh, 0E0h
		db 0FBh, 0C4h, 31h, 0FCh, 2, 0,	0D4h, 60h, 31h,	0FCh, 6
		db 66h,	0D4h, 68h, 31h,	0FCh, 0Eh, 0EEh, 0D4h, 88h, 33h
		db 0FCh, 8Bh, 0, 0, 0C0h, 0, 4,	31h, 0FCh, 8Bh,	0, 0C1h
		db 0CEh, 70h, 0, 23h, 0FCh, 78h, 0, 0, 3, 0, 0C0h, 0, 4
		db 23h,	0C0h, 0, 0C0h, 0, 0, 23h, 0FCh,	40h, 0,	0, 10h
		db 0, 0C0h, 0, 4, 23h, 0C0h, 0,	0C0h, 0, 0, 22h, 3Ch, 40h
		db 0, 0, 3, 61h, 22h, 22h, 3Ch,	60h, 0,	0, 3, 61h, 1Ah
		db 41h,	0F9h, 0, 0FFh, 2, 0, 32h, 3Ch, 7, 0, 20h, 0C0h
		db 51h,	0C9h, 0FFh, 0FCh, 58h, 78h, 0DFh, 0E0h,	46h, 0FCh
		db 23h,	0, 4Eh,	75h, 23h, 0C1h,	0, 0C0h, 0, 4, 32h, 3Ch
		db 7, 0FFh, 33h, 0C0h, 0, 0C0h,	0, 0, 51h, 0C9h, 0FFh
		db 0F8h, 4Eh, 75h, 48h,	0E7h, 0FFh, 0FEh, 4Eh, 0B9h, 0
		db 8Fh,	6Eh, 0FAh, 4Eh,	0B9h, 0, 8Fh, 40h, 0, 4Eh, 0B9h
		db 0, 8Fh, 45h,	4Ah, 4Ch, 0DFh,	7Fh, 0FFh, 42h,	38h, 0FFh
		db 0D1h, 4Eh, 73h, 61h,	0, 0, 0Ch, 61h,	0, 0, 0BAh, 61h
		db 0, 2, 1Eh, 4Eh, 75h,	7Eh, 0Fh, 0CEh,	38h, 0C1h, 3Dh
		db 66h,	2, 4Eh,	75h, 7Ch, 3, 0CCh, 47h,	67h, 1Ah, 70h
		db 1, 8, 7, 0, 1, 66h, 2, 44h, 40h, 32h, 38h, 0FBh, 0C2h
		db 74h,	5, 61h,	0, 0, 82h, 31h,	0C1h, 0FBh, 0C2h, 4Eh
		db 75h,	70h, 1,	8, 7, 0, 3, 66h, 2, 44h, 40h, 32h, 38h
		db 0FBh, 0C2h, 0D2h, 41h, 41h, 0FAh, 0,	8, 0D0h, 0C1h
		db 0D0h, 0D0h, 4Eh, 0D0h, 0, 0Ch, 0, 18h, 0, 24h, 0, 3Ch
		db 0, 34h, 0, 46h, 32h,	38h, 0FBh, 0C0h, 74h, 0Ah, 61h
		db 4Ch,	31h, 0C1h, 0FBh, 0C0h, 4Eh, 75h, 32h, 38h, 0DFh
		db 0F4h, 74h, 6, 61h, 3Eh, 31h,	0C1h, 0DFh, 0F4h, 4Eh
		db 75h,	0D0h, 40h, 32h,	38h, 0DFh, 0F6h, 74h, 7, 61h, 2Eh
		db 2, 41h, 0, 0Eh, 31h,	0C1h, 0DFh, 0F6h, 4Eh, 75h, 41h
		db 0F8h, 0E0h, 3Ah, 60h, 4, 41h, 0F8h, 0E0h, 38h, 32h
		db 10h,	74h, 7,	61h, 14h, 30h, 81h, 4Eh, 75h, 72h, 0, 12h
		db 38h,	0E0h, 4Ch, 74h,	1, 61h,	6, 11h,	0C1h, 0E0h, 4Ch
		db 4Eh,	75h, 0D2h, 40h,	6Ah, 2,	72h, 0,	0B2h, 42h, 6Fh
		db 2, 32h, 2, 4Eh, 75h,	61h, 0,	0, 18h,	61h, 0,	0, 56h
		db 61h,	0, 0, 7Eh, 61h,	0, 0, 0B0h, 61h, 0, 1, 0Ch, 61h
		db 0, 1, 3Ch, 4Eh, 75h,	41h, 0FAh, 3, 23h, 70h,	8, 72h
		db 8, 74h, 0, 4Ah, 78h,	0FBh, 0C2h, 66h, 4, 34h, 3Ch, 20h
		db 0, 61h, 0, 3, 0DEh, 30h, 38h, 0FBh, 0C0h, 0D0h, 40h
		db 41h,	0FAh, 0, 0Ch, 0D0h, 0C0h, 0D0h,	0D0h, 61h, 0, 3
		db 0DAh, 4Eh, 75h, 2, 12h, 2, 25h, 2, 38h, 2, 4Bh, 2, 5Eh
		db 2, 71h, 2, 84h, 2, 97h, 2, 0AAh, 2, 0BDh, 2,	0D0h, 41h
		db 0FAh, 2, 0ECh, 70h, 8, 72h, 0Ah, 74h, 0, 0Ch, 78h, 0
		db 1, 0FBh, 0C2h, 66h, 4, 34h, 3Ch, 20h, 0, 61h, 0, 3
		db 9Ah,	30h, 38h, 0DFh,	0F4h, 6, 40h, 0, 30h, 0D0h, 78h
		db 0FBh, 0C4h, 0D0h, 42h, 32h, 80h, 4Eh, 75h, 41h, 0FAh
		db 2, 0CBh, 70h, 8, 72h, 0Ch, 74h, 0, 0Ch, 78h,	0, 2, 0FBh
		db 0C2h, 66h, 4, 34h, 3Ch, 20h,	0, 61h,	0, 3, 6Eh, 70h
		db 6, 0C0h, 78h, 0DFh, 0F6h, 41h, 0FAh,	0, 0Ch,	0D0h, 0C0h
		db 0D0h, 0D0h, 61h, 0, 3, 6Ah, 4Eh, 75h, 2, 0B5h, 2, 0BBh
		db 2, 0C1h, 2, 0C7h, 41h, 0FAh,	2, 0CCh, 70h, 8, 72h, 0Eh
		db 74h,	0, 0Ch,	78h, 0,	3, 0FBh, 0C2h, 66h, 4, 34h, 3Ch
		db 20h,	0, 61h,	0, 3, 38h, 30h,	38h, 0E0h, 38h,	61h, 0
		db 0, 20h, 41h,	0FAh, 2, 0B5h, 70h, 8, 72h, 10h, 74h, 0
		db 0Ch,	78h, 0,	4, 0FBh, 0C2h, 66h, 4, 34h, 3Ch, 20h, 0
		db 61h,	0, 3, 16h, 30h,	38h, 0E0h, 3Ah,	0D0h, 40h, 41h
		db 0FAh, 0, 0Ch, 0D0h, 0C0h, 0D0h, 0D0h, 61h, 0, 3, 12h
		db 4Eh,	75h, 2,	94h, 2,	9Dh, 2,	0A6h, 2, 0AFh, 2, 0B8h
		db 2, 0C1h, 2, 0CAh, 2,	0D3h, 41h, 0FAh, 2, 40h, 70h, 8
		db 72h,	12h, 74h, 0, 0Ch, 78h, 0, 5, 0FBh, 0C2h, 66h, 4
		db 34h,	3Ch, 20h, 0, 61h, 0, 2,	0D8h, 70h, 0, 10h, 38h
		db 0E0h, 4Ch, 0D0h, 40h, 41h, 0FAh, 0, 0Ch, 0D0h, 0C0h
		db 0D0h, 0D0h, 61h, 0, 2, 0D2h,	4Eh, 75h, 2, 0ACh, 2, 0B4h
		db 41h,	0F9h, 0, 0FFh, 2, 0, 20h, 8, 32h, 38h, 0DFh, 0D2h
		db 34h,	3Ch, 7,	0, 4Eh,	0F9h, 0, 8Fh, 41h, 0B4h, 8, 38h
		db 0, 7, 0C1h, 3Dh, 66h, 2, 4Eh, 75h, 61h, 0, 0, 0BEh
		db 66h,	0Ah, 70h, 34h, 4Eh, 0B9h, 0, 8Fh, 6Eh, 76h, 4Eh
		db 75h,	31h, 0FCh, 0FFh, 0FFh, 0DFh, 0E6h, 61h,	0, 0, 82h
		db 0Ch,	78h, 0,	9, 0FBh, 0C0h, 64h, 48h, 0Ch, 78h, 0, 8
		db 0FBh, 0C0h, 66h, 10h, 42h, 78h, 0E0h, 1Ah, 42h, 78h
		db 0DFh, 0E0h, 31h, 0FCh, 0, 28h, 0DFh,	0DEh, 4Eh, 75h
		db 31h,	0F8h, 0FBh, 0C0h, 0DFh,	0F2h, 0Ch, 78h,	0, 7, 0FBh
		db 0C0h, 66h, 1Ah, 0Ch,	78h, 0,	1, 0DFh, 0F4h, 66h, 12h
		db 21h,	0FCh, 6, 6, 6, 6, 0DFh,	0FEh, 31h, 0FCh, 6, 0
		db 0E0h, 2, 42h, 78h, 0DFh, 0F4h, 31h, 0FCh, 0,	18h, 0DFh
		db 0DEh, 4Eh, 75h, 66h,	14h, 31h, 0F8h,	0E0h, 38h, 0E0h
		db 48h,	31h, 0FCh, 0, 0C8h, 0E0h, 8, 31h, 0FCh,	0, 50h
		db 0DFh, 0DEh, 4Eh, 75h, 31h, 0F8h, 0E0h, 38h, 0E0h, 48h
		db 31h,	0F8h, 0DFh, 0F4h, 0E0h,	1Ah, 31h, 0FCh,	0, 0C8h
		db 0E0h, 8, 31h, 0FCh, 0, 20h, 0DFh, 0DEh, 4Eh,	75h, 0E3h
		db 0F8h, 0E0h, 38h, 0E3h, 0F8h,	0E0h, 38h, 0E3h, 0F8h
		db 0E0h, 3Ah, 0E3h, 0F8h, 0E0h,	3Ah, 70h, 0, 10h, 38h
		db 0E0h, 4Ch, 0D0h, 40h, 41h, 0FBh, 0, 2Eh, 11h, 0D8h
		db 0E0h, 4Ch, 11h, 0D0h, 0E0h, 5Ch, 4Eh, 75h, 70h, 0Fh
		db 0C0h, 78h, 0FBh, 0C0h, 72h, 7, 0C2h,	78h, 0DFh, 0F4h
		db 3, 3Bh, 0, 4, 4Eh, 75h, 3Eh,	3Eh, 3Eh, 3Eh, 3Eh, 1Fh
		db 3Fh,	0FFh, 1, 0FFh, 0FFh, 0,	0, 0, 0, 0, 0, 0FEh, 0
		db 10h,	42h, 4Fh, 54h, 41h, 4Eh, 49h, 43h, 20h,	42h, 41h
		db 53h,	45h, 20h, 20h, 20h, 20h, 20h, 20h, 20h,	20h, 0
		db 53h,	50h, 45h, 45h, 44h, 20h, 53h, 4Ch, 49h,	44h, 45h
		db 52h,	20h, 20h, 20h, 20h, 20h, 20h, 20h, 20h,	0, 41h
		db 4Dh,	41h, 5Ah, 49h, 4Eh, 47h, 20h, 41h, 52h,	45h, 4Eh
		db 41h,	20h, 20h, 20h, 20h, 20h, 20h, 20h, 0, 54h, 45h
		db 43h,	48h, 4Eh, 4Fh, 20h, 54h, 4Fh, 57h, 45h,	52h, 20h
		db 20h,	20h, 20h, 20h, 20h, 20h, 20h, 0, 4Dh, 41h, 52h
		db 49h,	4Eh, 41h, 20h, 4Dh, 41h, 44h, 4Eh, 45h,	53h, 53h
		db 20h,	20h, 20h, 20h, 20h, 20h, 0, 54h, 52h, 41h, 49h
		db 4Eh,	49h, 4Eh, 47h, 20h, 20h, 20h, 20h, 20h,	20h, 20h
		db 20h,	20h, 20h, 20h, 20h, 0, 49h, 4Eh, 54h, 52h, 4Fh
		db 44h,	55h, 43h, 54h, 49h, 4Fh, 4Eh, 20h, 20h,	20h, 20h
		db 20h,	20h, 20h, 20h, 0, 57h, 4Fh, 52h, 4Ch, 44h, 20h
		db 45h,	4Eh, 54h, 52h, 41h, 4Eh, 43h, 45h, 20h,	20h, 20h
		db 20h,	20h, 20h, 0, 4Eh, 4Fh, 54h, 20h, 55h, 53h, 45h
		db 44h,	20h, 20h, 20h, 20h, 20h, 20h, 20h, 20h,	20h, 20h
		db 20h,	20h, 0,	42h, 4Fh, 4Eh, 55h, 53h, 20h, 53h, 54h
		db 41h,	47h, 45h, 20h, 20h, 20h, 20h, 20h, 20h,	20h, 20h
		db 20h,	0, 53h,	50h, 45h, 43h, 49h, 41h, 4Ch, 20h, 53h
		db 54h,	41h, 47h, 45h, 20h, 20h, 20h, 20h, 20h,	20h, 20h
		db 0, 50h, 4Ch,	41h, 43h, 45h, 20h, 20h, 20h, 20h, 20h
		db 0, 4Ch, 45h,	56h, 45h, 4Ch, 20h, 20h, 20h, 20h, 20h
		db 0, 41h, 54h,	2Dh, 54h, 49h, 4Dh, 45h, 20h, 20h, 20h
		db 0, 50h, 4Ch,	41h, 59h, 45h, 52h, 53h, 20h, 20h, 20h
		db 0, 4Dh, 4Fh,	52h, 4Eh, 49h, 4Eh, 47h, 0, 44h, 41h, 59h
		db 20h,	20h, 20h, 20h, 0, 53h, 55h, 4Eh, 53h, 45h, 54h
		db 20h,	0, 4Eh,	49h, 47h, 48h, 54h, 20h, 20h, 0, 0, 50h
		db 4Ch,	41h, 59h, 45h, 52h, 20h, 20h, 20h, 20h,	0, 43h
		db 4Fh,	4Dh, 42h, 49h, 20h, 20h, 20h, 20h, 20h,	0, 4Dh
		db 49h,	47h, 48h, 54h, 59h, 20h, 20h, 20h, 20h,	0, 2Ah
		db 2Ah,	2Ah, 2Ah, 2Ah, 2Ah, 2Ah, 2Ah, 2Ah, 2Ah,	0, 4Bh
		db 4Eh,	55h, 43h, 4Bh, 4Ch, 45h, 53h, 20h, 20h,	0, 43h
		db 48h,	41h, 52h, 4Dh, 59h, 20h, 42h, 45h, 45h,	0, 56h
		db 45h,	43h, 54h, 4Fh, 52h, 20h, 20h, 20h, 20h,	0, 42h
		db 4Fh,	4Dh, 42h, 20h, 20h, 20h, 20h, 20h, 20h,	0, 48h
		db 45h,	41h, 56h, 59h, 20h, 20h, 20h, 20h, 20h,	0, 45h
		db 53h,	50h, 49h, 4Fh, 20h, 20h, 20h, 20h, 20h,	0, 31h
		db 20h,	50h, 4Ch, 41h, 59h, 45h, 52h, 20h, 0, 32h, 20h
		db 50h,	4Ch, 41h, 59h, 45h, 52h, 53h, 0, 43h, 0F9h, 0
		db 0FFh, 2, 0, 0D0h, 40h, 0D2h,	0C0h, 0EFh, 49h, 0D2h
		db 0C1h, 36h, 38h, 0FBh, 0C4h, 30h, 2, 10h, 18h, 67h, 6
		db 0D0h, 43h, 32h, 0C0h, 60h, 0F4h, 4Eh, 75h, 0FFh, 0FFh
		db 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
		db 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
		db 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
		db 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
		db 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
		db 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
		db 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
		db 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
		db 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
		db 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
		db 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
		db 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
		db 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
		db 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
		db 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
		db 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
		db 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
		db 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
		db 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
		db 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
		db 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
		db 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
		db 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
		db 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
		db 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
		db 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
		db 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
		db 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
		db 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
		db 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
		db 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
		db 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
		db 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
		db 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
byte_1BF7:	db 0FFh			; DATA XREF: RAM:0080w
					; StopAllSound+24w ...
unk_1BF8:	db 0FFh			; DATA XREF: RAM:0077o
					; UpdateTrack:loc_EF6o
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
byte_1C04:	db 0FFh			; DATA XREF: RAM:0085w	RAM:0088o ...
		db 0FFh
byte_1C06:	db 0FFh			; DATA XREF: DoFading+24o
					; StopAllSound+27w ...
		db 0FFh
		db 0FFh
byte_1C09:	db 0FFh			; DATA XREF: PlaySoundIDr
					; StopAllSound-1E9w ...
byte_1C0A:	db 0FFh, 0FFh, 0FFh	; DATA XREF: StopAllSound+3o
					; DoSoundQueue+5o ...
byte_1C0D:	db 0FFh			; DATA XREF: DoPause+13r RAM:076Cw ...
byte_1C0E:	db 0FFh			; DATA XREF: RAM:0774w
					; DoFading:ApplyFadingr
byte_1C0F:	db 0FFh			; DATA XREF: RAM:0771w	DoFading+Br ...
unk_1C10:	db 0FFh			; DATA XREF: DoPauseo
byte_1C11:	db 0FFh			; DATA XREF: DoPause:loc_731r
					; cf02_MusPausew
byte_1C12:	db 0FFh			; DATA XREF: StopAllSound+39w
					; SendFM3SpcModew
byte_1C13:	db 0FFh			; DATA XREF: PlaySoundID+82w
					; DoTempo+3o ...
byte_1C14:	db 0FFh			; DATA XREF: PlaySoundID+85w DoTempor	...
byte_1C15:	db 0FFh			; DATA XREF: PlaySoundID+166w
					; cfE3_SilenceTrk+111w
byte_1C16:	db 0FFh			; DATA XREF: cfE2_SetCommw
byte_1C17:	db 0FFh			; DATA XREF: DoSoundQueue+2w
byte_1C18:	db 0FFh			; DATA XREF: PlaySoundID+1Ew
					; DoSoundQueue+1Er ...
byte_1C19:	db 0FFh			; DATA XREF: UpdateAll+10w
					; UpdateSFXTracks+2w ...
unk_1C1A:	db 0FFh			; DATA XREF: GetFM3FreqPtr+8o
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
unk_1C22:	db 0FFh			; DATA XREF: GetFM3FreqPtr+Co
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
unk_1C2A:	db 0FFh			; DATA XREF: GetFM3FreqPtro
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
byte_1C32:	db 0FFh			; DATA XREF: GetSFXChnPtrs+27w
word_1C33:	dw 0FFFFh		; DATA XREF: PlaySoundID+8Cw
					; PlaySoundID+ABr ...
word_1C35:	dw 0FFFFh		; DATA XREF: PlaySoundID+92w
					; PlaySoundID+9Fr ...
word_1C37:	dw 0FFFFh		; DATA XREF: GetFMInsPtrr
					; PlaySoundID+79w ...
word_1C39:	dw 0FFFFh		; DATA XREF: PlaySoundID+162w
					; PlaySoundID+1BDr
byte_1C3B:	db 0FFh			; DATA XREF: PlaySoundID+170w
					; PlaySoundID+19Ar
		db 0FFh
byte_1C3D:	db 0FFh			; DATA XREF: cfE3_SilenceTrk+114r
					; cfE3_SilenceTrk+1AFw	...
		db 0FFh
		db 0FFh
byte_1C40:	db [ 30h ], 0FFh	; DATA XREF: UpdateAll+2Ao
					; UpdateAll+30o ...
		db [ 30h ], 0FFh
		db [ 30h ], 0FFh
		db [ 30h ], 0FFh
		db [ 30h ], 0FFh
		db [ 22h ], 0FFh
		db 6, 0, 1, 0A0h, 6, 4
		db [ 2 ], 0
		db 6, 0, 1, 0A0h, 6, 4
byte_1D60:	db 0, 0, 6, 0, 1, 0A8h,	6, 0, 1, 0A8h, 6, 0, 1,	0A8h, 6
					; DATA XREF: PlaySoundID+CDo
					; StopDrumPSG+1w
		db 0, 1, 0A8h, 6, 0, 1,	0A8h, 6, 0, 1, 0A8h, 6,	0, 1, 0A8h
		db 6, 0, 1, 0A8h, 6, 0,	1, 0A8h, 6, 0, 1, 0A8h,	6, 0, 1
		db 0A8h, 6, 0
byte_1D90:	db 1, 0A8h, 6, 0, 1, 0A8h, 6, 0, 1, 0A8h, 6, 0,	1, 0A8h
					; DATA XREF: StopDrumPSG+4w
		db 6, 0, 1, 0A8h, 6, 0,	1, 0A8h, 6, 0, 1, 0A8h,	6, 0, 1
		db 0A8h, 6, 0, 1, 0A8h,	6, 0, 1, 0A8h, 6, 0, 1,	0A8h, 6
		db 0, 1, 0A8h, 6, 0, 1,	0A8h, 6, 0, 1, 0A8h, 6,	0, 1, 0A8h
		db 6, 0, 1, 0A8h, 6, 0,	1, 0A8h, 6, 0, 1, 0A4h,	0C0h, 0
		db 8, 0, 6, 0, 1, 0A4h,	0C0h, 0, 8, 0, 6, 0, 1,	0A8h, 6
		db 0, 1, 0A8h, 6, 0, 1,	0A8h, 6, 0
byte_1DF0:	db 1, 0A8h, 6, 0, 1, 0A8h, 6, 0, 1, 0A8h, 6, 0,	1, 0A8h
					; DATA XREF: PlaySoundID+F7o
		db 6, 0, 1, 0A8h, 6, 0,	1, 0A8h, 6, 0, 1, 0A8h,	6, 0, 1
		db 0A8h, 6, 0, 1, 0A8h,	6, 0, 1, 0A8h, 6, 0, 1,	0A8h, 6
		db 0, 1, 0A8h, 6, 0
		db    1
		db 0A8h	; ®
		db    6
		db    0
		db    1
		db 0A8h	; ®
		db    6
		db    0
		db    1
		db 0A8h	; ®
		db    6
		db    0
		db    1
		db 0A8h	; ®
		db    6
		db    0
		db    1
		db 0A8h	; ®
		db    6
		db    0
		db    1
		db 0A8h	; ®
		db    6
		db    0
		db    1
		db 0A8h	; ®
		db    6
		db    0
		db    1
		db 0A8h	; ®
		db    6
		db    0
		db    1
		db 0A8h	; ®
		db    6
		db    0
		db    1
		db 0A8h	; ®
		db    6
		db    0
		db    1
		db 0A8h	; ®
		db    6
		db    0
		db    1
		db 0A8h	; ®
		db    6
		db    0
		db    1
		db 0A8h	; ®
		db    6
		db    0
		db    1
		db 0B0h	; ∞
		db    6
		db    0
		db    1
		db 0B0h	; ∞
		db    6
		db    0
		db    1
		db 0B0h	; ∞
		db    6
		db    0
		db    1
		db 0B0h	; ∞
		db    6
		db    0
		db    1
		db 0B0h	; ∞
		db    6
		db    0
		db    1
		db 0B0h	; ∞
		db    6
		db    0
		db    1
		db 0B0h	; ∞
		db    6
		db    0
		db    1
		db 0B0h	; ∞
		db    6
		db    0
		db    1
		db 0A8h	; ®
		db    6
		db    0
		db    1
		db 0A8h	; ®
		db    6
		db    0
		db    1
		db 0A8h	; ®
		db    6
		db    0
		db    1
		db 0A8h	; ®
		db    6
		db    0
		db    1
		db 0A8h	; ®
		db    6
		db    0
		db    1
		db 0A8h	; ®
		db    6
		db    0
		db    1
		db 0A8h	; ®
		db    6
		db    0
		db    1
		db 0A8h	; ®
		db    6
		db    0
		db    1
		db 0A8h	; ®
		db    6
		db    0
		db    1
		db 0A8h	; ®
		db    6
		db    0
		db    1
		db 0A8h	; ®
		db    6
		db    0
		db    1
		db 0A8h	; ®
		db    6
		db    0
		db    1
		db 0A8h	; ®
		db    6
		db    0
		db    1
		db 0A8h	; ®
		db    6
		db    0
		db    1
		db 0A8h	; ®
		db    6
		db    0
unk_1EB0:	db    1			; DATA XREF: UpdateSFXTracks+15o
					; DoPause+39o
		db 0A8h	; ®
		db    6
		db    0
		db    1
		db 0A8h	; ®
		db    6
		db    0
		db    1
		db 0A8h	; ®
		db    6
		db    0
		db    1
		db 0A8h	; ®
		db    6
		db    0
		db    1
		db 0A8h	; ®
		db    6
		db    0
		db    1
		db 0A8h	; ®
		db    6
		db    0
		db    1
		db 0A8h	; ®
		db    6
		db    0
		db    1
		db 0A8h	; ®
		db    6
		db    0
		db    1
		db 0A8h	; ®
		db    6
		db    0
		db    1
		db 0F8h	; ¯
		db    6
		db    0
		db    1
		db 0F8h	; ¯
		db    6
		db    0
		db    1
		db 0F8h	; ¯
		db    6
		db    0
		db    1
		db 0F8h	; ¯
		db    6
		db    0
		db    1
		db 0F8h	; ¯
		db    6
		db    0
		db    1
		db 0F8h	; ¯
		db    6
		db    0
		db    1
		db 0F8h	; ¯
		db    6
		db    0
		db    1
		db 0F8h	; ¯
		db 0A3h	; £
		db  70h	; p
		db    0
		db    9
		db 0A0h	; †
		db  4Eh	; N
		db    0
		db    9
		db 0AFh	; Ø
		db 0FEh	; ˛
		db    0
		db    9
		db    0
		db    0
		db    0
		db    0
		db  2Fh	; /
		db    6
		db    0
		db    2
		db  2Fh	; /
		db  16h
		db  40h	; @
		db    9
		db 0D1h	; —
		db    6
		db  40h	; @
		db    1
		db 0C9h	; …
		db  1Ch
		db    1
		db  1Eh
		db  4Fh	; O
		db  22h	; "
		db  90h	; ê
		db    6
		db  41h	; A
		db  0Bh
		db  40h	; @
		db  0Eh
		db  4Fh	; O
		db  26h	; &
		db  61h	; a
		db 0F6h	; ˆ
		db  60h	; `
		db 0F6h	; ˆ
		db    0
		db  2Bh	; +
		db    0
		db    9
		db    0
		db 0F0h	; 
		db    6
		db    0
		db    1
		db 0D8h	; ÿ
		db    6
		db    0
		db    2
		db  40h	; @
		db    6
		db    0
		db    2
		db  40h	; @
		db    6
		db    0
		db    2
		db  40h	; @
		db    6
		db    0
		db    2
		db  40h	; @
		db    6
		db    0
		db  13h
		db  34h	; 4
		db    6
		db    0
		db    1
		db 0A8h	; ®
		db    6
		db    0
		db  12h
		db  80h	; Ä
		db    6
		db    0
		db  12h
		db  50h	; P
		db  2Fh	; /
		db    6
		db    0
		db    2
		db  2Fh	; /
		db  16h
		db  40h	; @
		db    9
		db 0D1h	; —
		db    6
		db  40h	; @
		db    1
		db 0C9h	; …
		db  1Ch
		db    1
		db  1Eh
		db  4Fh	; O
		db  22h	; "
		db  90h	; ê
		db    6
		db  41h	; A
		db  0Bh
		db  40h	; @
		db  0Eh
		db  4Fh	; O
		db  26h	; &
		db  61h	; a
		db 0F6h	; ˆ
		db  60h	; `
		db 0F6h	; ˆ
		db    0
		db  2Bh	; +
		db    0
		db    9
		db    0
		db 0F0h	; 
		db    6
		db    0
		db    2
		db  20h
		db    6
		db    0
		db    2
		db  40h	; @
		db    6
		db    0
		db    2
		db  40h	; @
		db    6
		db    0
		db    2
		db  40h	; @
		db 0C0h	; ¿
		db    0
		db    0
		db    4
		db    6
		db    0
		db    2
		db  40h	; @
		db    6
		db    0
		db    2
		db  40h	; @
		db    6
		db    0
		db    2
		db  40h	; @
		db    6
		db    0
		db    3
		db    8
		db    0
		db  0Bh
		db    0
		db    9
		db  91h	; ë
		db  32h	; 2
		db 0E0h	; ‡
		db    0
		db  80h	; Ä
		db  10h
		db 0E0h	; ‡
		db 0E2h	; ‚
		db  80h	; Ä
		db  17h
		db 0E0h	; ‡
		db    0
		db  80h	; Ä
		db  14h
		db 0E0h	; ‡
		db    1
		db  80h	; Ä
		db  15h
		db 0E0h	; ‡
		db    0
		db  80h	; Ä
		db  16h
		db 0E0h	; ‡
		db    1
		db  80h	; Ä
		db  11h
		db 0E0h	; ‡
		db    0
		db  80h	; Ä
		db  13h
		db  80h	; Ä
		db  12h
		db 0D1h	; —
		db  12h
		db 0DFh	; ﬂ
		db  13h
		db  41h	; A
		db  2Eh	; .
		db 0DEh	; ﬁ
		db  13h
		db 0E0h	; ‡
		db    0
		db  81h	; Å
		db 0EAh	; Í
		db  80h	; Ä
		db 0E1h	; ·
		db 0E0h	; ‡
		db  20h
		db  40h	; @
		db  0Eh
		db  50h	; P
		db 0E9h	; È
		db  20h
		db    8
		db  8Bh	; ã
		db 0FCh	; ¸
		db 0D0h	; –
		db  0Fh
		db 0D1h	; —
		db  10h
		db 0B0h	; ∞
		db  3Dh	; =
		db  21h	; !
		db    2
		db 0D1h	; —
		db  0Fh
		db 0D2h	; “
		db  10h
		db  93h	; ì
		db  11h
		db  60h	; `
		db  16h
		db  43h	; C
		db  10h
		db  22h	; "
		db    2
		db  8Fh	; è
		db 0FBh	; ˚
		db  72h	; r
		db    4
		db 0B0h	; ∞
		db  33h	; 3
		db    0
		db    9
		db 0DEh	; ﬁ
		db  0Bh
		db  4Eh	; N
		db  0Bh
		db    0
		db    9
		db 0D1h	; —
		db  0Bh
		db 0E0h	; ‡
		db    0
		db  21h	; !
		db    2
		db 0D0h	; –
		db  0Ah
		db 0D1h	; —
		db    6
		db 0A0h	; †
		db  1Bh
		db  21h	; !
		db    2
		db 0FEh	; ˛
		db  10h
; end of 'RAM'


		end
