cls
cd /D "%~dp0"
call "AAZ\128x128\recmp.bat"
cd /D "%~dp0"
call "AAZ\16x16\recmp.bat"
cd /D "%~dp0"
call "AAZ\8x8\recmp.bat"
cd /D "%~dp0"
call "AAZ\BG\recmp.bat"
cd /D "%~dp0"
call "AAZ\FG\recmp.bat"
cd /D "%~dp0"
call "BBZ\128x128\recmp.bat"
cd /D "%~dp0"
call "BBZ\16x16\recmp.bat"
cd /D "%~dp0"
call "BBZ\8x8\recmp.bat"
cd /D "%~dp0"
call "BBZ\BG\recmp.bat"
cd /D "%~dp0"
call "BBZ\FG\recmp.bat"
cd /D "%~dp0"
call "Entrance\128x128\recmp.bat"
cd /D "%~dp0"
call "Entrance\16x16\recmp.bat"
cd /D "%~dp0"
call "Entrance\8x8\recmp.bat"
cd /D "%~dp0"
call "Entrance\BG\recmp.bat"
cd /D "%~dp0"
call "Entrance\FG\recmp.bat"
cd /D "%~dp0"
call "Intro\128x128\recmp.bat"
cd /D "%~dp0"
call "Intro\16x16\recmp.bat"
cd /D "%~dp0"
call "Intro\8x8\recmp.bat"
cd /D "%~dp0"
call "Intro\BG\recmp.bat"
cd /D "%~dp0"
call "Intro\FG\recmp.bat"
cd /D "%~dp0"
call "MMZ\128x128\recmp.bat"
cd /D "%~dp0"
call "MMZ\16x16\recmp.bat"
cd /D "%~dp0"
call "MMZ\8x8\recmp.bat"
cd /D "%~dp0"
call "MMZ\BG\recmp.bat"
cd /D "%~dp0"
call "MMZ\FG\recmp.bat"
cd /D "%~dp0"
call "SSZ\128x128\recmp.bat"
cd /D "%~dp0"
call "SSZ\16x16\recmp.bat"
cd /D "%~dp0"
call "SSZ\8x8\recmp.bat"
cd /D "%~dp0"
call "SSZ\BG\recmp.bat"
cd /D "%~dp0"
call "SSZ\FG\recmp.bat"
cd /D "%~dp0"
call "TTZ\128x128\recmp.bat"
cd /D "%~dp0"
call "TTZ\16x16\recmp.bat"
cd /D "%~dp0"
call "TTZ\8x8\recmp.bat"
cd /D "%~dp0"
call "TTZ\BG\recmp.bat"
cd /D "%~dp0"
call "TTZ\FG\recmp.bat"
cd /D "%~dp0"
call "Tutorial\128x128\recmp.bat"
cd /D "%~dp0"
call "Tutorial\16x16\recmp.bat"
cd /D "%~dp0"
call "Tutorial\8x8\recmp.bat"
cd /D "%~dp0"
call "Tutorial\BG\recmp.bat"
cd /D "%~dp0"
call "Tutorial\FG\recmp.bat"
cls