cd /D "%~dp0"
KENSSharp.exe -r e "0_15MN.bin"
KENSSharp.exe -r e "0_Boss.bin"
KENSSharp.exe -r e "1_3MN.bin"
KENSSharp.exe -r e "1_12MN.bin"
KENSSharp.exe -r e "1_45MN.bin"
KENSSharp.exe -r e "2_15MN.bin"
KENSSharp.exe -r e "3_3MD.bin"
KENSSharp.exe -r e "3_3SN.bin"
KENSSharp.exe -r e "3_12MD.bin"
KENSSharp.exe -r e "3_12SN.bin"
KENSSharp.exe -r e "3_45MD.bin"
KENSSharp.exe -r e "3_45SN.bin"