Cls
CD "%~dp0\"

REM Optimize all MIDI Songs
REM SMPSOpt.exe S1 "81\Out\Mus81 - GHZ.bin" "81\Out\Mus81 - GHZ.bin"

REM Moves all compiled songs from each folder into SMPSPlay
REM Music

Copy /y /b "01\Out\01 Door Into Summer.bin" "Preview\Data\Knuckles Maniax\01 Door Into Summer.skc"
Copy /y /b "02\Out\02 Electoria.bin" "Preview\Data\Knuckles Maniax\02 Electoria.skc"
REM Copy /y /b "03\Out\03 Speed Of Sound.bin" "Preview\Data\Knuckles Maniax\03 Speed Of Sound.skc"
REM Copy /y /b "04\Out\04 Seascape.bin" "Preview\Data\Knuckles Maniax\04 Seascape.skc"
REM Copy /y /b "05\Out\05 Midnight Greenhouse.bin" "Preview\Data\Knuckles Maniax\05 Midnight Greenhouse.skc"
REM Copy /y /b "06\Out\06 New Moon.bin" "Preview\Data\Knuckles Maniax\06 New Moon.skc"
Copy /y /b "07\Out\07 Labyrinth.bin" "Preview\Data\Knuckles Maniax\07 Labyrinth.skc"
Copy /y /b "08\Out\08 Trial And Error.bin" "Preview\Data\Knuckles Maniax\08 Trial And Error.skc"
Copy /y /b "09\Out\09 Walkin.bin" "Preview\Data\Knuckles Maniax\09 Walkin.skc"
Copy /y /b "0A\Out\0A Hyper-Hyper.bin" "Preview\Data\Knuckles Maniax\0A Hyper-Hyper.skc"
Copy /y /b "0B\Out\0B Evening Star.bin" "Preview\Data\Knuckles Maniax\0B Evening Star.skc"
Copy /y /b "0C\Out\0C Moonrise.bin" "Preview\Data\Knuckles Maniax\0C Moonrise.skc"
REM Copy /y /b "0D\Out\0D Overture.bin" "Preview\Data\Knuckles Maniax\0D Overture.skc"
REM Copy /y /b "0E\Out\0E This Horizon.bin" "Preview\Data\Knuckles Maniax\0E This Horizon.skc"
Copy /y /b "0F\Out\0F Take Off.bin" "Preview\Data\Knuckles Maniax\0F Take Off.skc"
Copy /y /b "10\Out\10 Combination.bin" "Preview\Data\Knuckles Maniax\10 Combination.skc"
Copy /y /b "11\Out\11 Take A Nap.bin" "Preview\Data\Knuckles Maniax\11 Take A Nap.skc"
Copy /y /b "12\Out\12 Surging Power.bin" "Preview\Data\Knuckles Maniax\12 Surging Power.skc"
Copy /y /b "13\Out\13 Mechanical Dance.bin" "Preview\Data\Knuckles Maniax\13 Mechanical Dance.skc"
REM Copy /y /b "14\Out\14 Tube Panic.bin" "Preview\Data\Knuckles Maniax\14 Tube Panic.skc"
REM Copy /y /b "14\Out\14 Tube Panic [extra drums].bin" "Preview\Data\Knuckles Maniax\14 Tube Panic [extra drums].skc"
Copy /y /b "15\Out\15 Crystal Nightmare.bin" "Preview\Data\Knuckles Maniax\15 Crystal Nightmare.skc"
REM Copy /y /b "16\Out\16 Childs Song.bin" "Preview\Data\Knuckles Maniax\16 Childs Song.skc"
REM Copy /y /b "17\Out\17 Soda Pop.bin" "Preview\Data\Knuckles Maniax\17 Soda Pop.skc"
REM Copy /y /b "18\Out\18 Pendulum.bin" "Preview\Data\Knuckles Maniax\18 Pendulum.skc"
REM Copy /y /b "19\Out\19 Silver Screen.bin" "Preview\Data\Knuckles Maniax\19 Silver Screen.skc"
Copy /y /b "1A\Out\1A Tachy Touch.bin" "Preview\Data\Knuckles Maniax\1A Tachy Touch.skc"
Copy /y /b "1B\Out\1B Chaotic World.bin" "Preview\Data\Knuckles Maniax\1B Chaotic World.skc"
Copy /y /b "1C\Out\1C Surprise.bin" "Preview\Data\Knuckles Maniax\1C Surprise.skc"
Copy /y /b "1D\Out\1D Nice Meeting You.bin" "Preview\Data\Knuckles Maniax\1D Nice Meeting You.skc"
Copy /y /b "1E\Out\1E Have A Happy Day.bin" "Preview\Data\Knuckles Maniax\1E Have A Happy Day.skc"
Copy /y /b "1F\Out\1F Reach The Goal.bin" "Preview\Data\Knuckles Maniax\1F Reach The Goal.skc"
Copy /y /b "20\Out\20 High Five.bin" "Preview\Data\Knuckles Maniax\20 High Five.skc"
REM Copy /y /b "21\Out\21 Decision.bin" "Preview\Data\Knuckles Maniax\21 Decision.skc"
Copy /y /b "22\Out\22 From Party To Party.bin" "Preview\Data\Knuckles Maniax\22 From Party To Party.skc"
Copy /y /b "23\Out\23 Have Some Fun.bin" "Preview\Data\Knuckles Maniax\23 Have Some Fun.skc"
Copy /y /b "24\Out\24 Oriental Legend.bin" "Preview\Data\Knuckles Maniax\24 Oriental Legend.skc"
Copy /y /b "25\Out\25 Steel Heart.bin" "Preview\Data\Knuckles Maniax\25 Steel Heart.skc"
Copy /y /b "26\Out\26 Tribute.bin" "Preview\Data\Knuckles Maniax\26 Tribute.skc"
Copy /y /b "27\Out\27 Destructive Power.bin" "Preview\Data\Knuckles Maniax\27 Destructive Power.skc"
Copy /y /b "28\Out\28 Just Another Day.bin" "Preview\Data\Knuckles Maniax\28 Just Another Day.skc"
Copy /y /b "29\Out\29 Decision 2nd.bin" "Preview\Data\Knuckles Maniax\29 Decision 2nd.skc"
Copy /y /b "Test\PWM_PSG_Test\Out\Soundtest.bin" "Preview\Data\Knuckles Maniax\Soundtest.skc"

REM SFX
Copy /y /b "5F\Out\5F.bin" "Preview\Data\Knuckles Maniax\SFX\5F.sf3"


REM Copies all finalized ASM files to working project dir for recompilation into driver
REM Music

Copy /Y "01\Out\KC.asm" "..\..\Sound\Music\ASM\01 Door Into Summer.asm"
Copy /Y "02\Out\KC.asm" "..\..\Sound\Music\ASM\02 Electoria.asm"
REM Copy /Y "03\Out\KC.asm" "..\..\Sound\Music\ASM\03 Speed Of Sound.asm"
REM Copy /Y "04\Out\KC.asm" "..\..\Sound\Music\ASM\04 Seascape.asm"
REM Copy /Y "05\Out\KC.asm" "..\..\Sound\Music\ASM\05 Midnight Greenhouse.asm"
REM Copy /Y "06\Out\KC.asm" "..\..\Sound\Music\ASM\06 New Moon.asm"
Copy /Y "07\Out\KC.asm" "..\..\Sound\Music\ASM\07 Labyrinth.asm"
Copy /Y "08\Out\KC.asm" "..\..\Sound\Music\ASM\08 Trial And Error.asm"
Copy /Y "09\Out\KC.asm" "..\..\Sound\Music\ASM\09 Walkin.asm"
Copy /Y "0A\Out\KC.asm" "..\..\Sound\Music\ASM\0A Hyper-Hyper.asm"
Copy /Y "0B\Out\KC.asm" "..\..\Sound\Music\ASM\0B Evening Star.asm"
Copy /Y "0C\Out\KC.asm" "..\..\Sound\Music\ASM\0C Moonrise.asm"
REM Copy /Y "0D\Out\KC.asm" "..\..\Sound\Music\ASM\0D Overture.asm"
REM Copy /Y "0E\Out\KC.asm" "..\..\Sound\Music\ASM\0E This Horizon.asm"
Copy /Y "0F\Out\KC.asm" "..\..\Sound\Music\ASM\0F Take Off.asm"
Copy /Y "10\Out\KC.asm" "..\..\Sound\Music\ASM\10 Combination.asm"
Copy /Y "11\Out\KC.asm" "..\..\Sound\Music\ASM\11 Take A Nap.asm"
Copy /Y "12\Out\KC.asm" "..\..\Sound\Music\ASM\12 Surging Power.asm"
Copy /Y "13\Out\KC.asm" "..\..\Sound\Music\ASM\13 Mechanical Dance.asm"
REM Copy /Y "14\Out\KC.asm" "..\..\Sound\Music\ASM\14 Tube Panic.asm"
REM Copy /Y "15\Out\KC.asm" "..\..\Sound\Music\ASM\15 Crystal Nightmare.asm"
REM Copy /Y "16\Out\KC.asm" "..\..\Sound\Music\ASM\16 Childs Song.asm"
REM Copy /Y "17\Out\KC.asm" "..\..\Sound\Music\ASM\17 Soda Pop.asm"
REM Copy /Y "18\Out\KC.asm" "..\..\Sound\Music\ASM\18 Pendulum.asm"
REM Copy /Y "19\Out\KC.asm" "..\..\Sound\Music\ASM\19 Silver Screen.asm"
Copy /Y "1A\Out\KC.asm" "..\..\Sound\Music\ASM\1A Tachy Touch.asm"
Copy /Y "1B\Out\KC.asm" "..\..\Sound\Music\ASM\1B Chaotic World.asm"
Copy /Y "1C\Out\KC.asm" "..\..\Sound\Music\ASM\1C Surprise.asm"
Copy /Y "1D\Out\KC.asm" "..\..\Sound\Music\ASM\1D Nice Meeting You.asm"
Copy /Y "1E\Out\KC.asm" "..\..\Sound\Music\ASM\1E Have A Happy Day.asm"
Copy /Y "1F\Out\KC.asm" "..\..\Sound\Music\ASM\1F Reach The Goal.asm"
Copy /Y "20\Out\KC.asm" "..\..\Sound\Music\ASM\20 High Five.asm"
REM Copy /Y "21\Out\KC.asm" "..\..\Sound\Music\ASM\21 Decision.asm"
Copy /Y "22\Out\KC.asm" "..\..\Sound\Music\ASM\22 From Party to Party.asm"
Copy /Y "23\Out\KC.asm" "..\..\Sound\Music\ASM\23 Have Some Fun.asm"
Copy /Y "24\Out\KC.asm" "..\..\Sound\Music\ASM\24 Oriental Legend.asm"
Copy /Y "25\Out\KC.asm" "..\..\Sound\Music\ASM\25 Steel Heart.asm"
Copy /Y "26\Out\KC.asm" "..\..\Sound\Music\ASM\26 Tribute.asm"
Copy /Y "27\Out\KC.asm" "..\..\Sound\Music\ASM\27 Destructive Power.asm"
Copy /Y "28\Out\KC.asm" "..\..\Sound\Music\ASM\28 Just Another Day.asm"
Copy /Y "29\Out\KC.asm" "..\..\Sound\Music\ASM\29 Decision 2nd.asm"

REM SFX
Copy /Y "5F\Out\KC.asm" "..\..\Sound\Music\ASM\5F.asm"
pause