Cls
CD "%~dp0\"

REM Optimize all MIDI Songs
REM SMPSOpt.exe S1 "81\Out\Mus81 - GHZ.bin" "81\Out\Mus81 - GHZ.bin"

REM Moves all compiled songs from each folder into SMPSPlay
Copy /y /b "01\Out\01 Door Into Summer.bin" "Preview\Data\Knuckles Maniax\01 Door Into Summer.skc"
Copy /y /b "02\Out\02 Electoria.bin" "Preview\Data\Knuckles Maniax\02 Electoria.skc"
Copy /y /b "03\Out\03 Speed Of Sound.bin" "Preview\Data\Knuckles Maniax\03 Speed Of Sound.skc"
Copy /y /b "04\Out\04 Seascape.bin" "Preview\Data\Knuckles Maniax\04 Seascape.skc"
Copy /y /b "05\Out\05 Midnight Greenhouse.bin" "Preview\Data\Knuckles Maniax\05 Midnight Greenhouse.skc"
Copy /y /b "06\Out\06 New Moon.bin" "Preview\Data\Knuckles Maniax\06 New Moon.skc"
Copy /y /b "07\Out\07 Labyrinth.bin" "Preview\Data\Knuckles Maniax\07 Labyrinth.skc"
Copy /y /b "08\Out\08 Trial And Error.bin" "Preview\Data\Knuckles Maniax\08 Trial And Error.skc"
Copy /y /b "09\Out\09 Walkin.bin" "Preview\Data\Knuckles Maniax\09 Walkin.skc"
Copy /y /b "0A\Out\0A Hyper-Hyper.bin" "Preview\Data\Knuckles Maniax\0A Hyper-Hyper.skc"
Copy /y /b "0B\Out\0B Evening Star.bin" "Preview\Data\Knuckles Maniax\0B Evening Star.skc"
Copy /y /b "0C\Out\0C Moonrise.bin" "Preview\Data\Knuckles Maniax\0C Moonrise.skc"
Copy /y /b "0D\Out\0D Overture.bin" "Preview\Data\Knuckles Maniax\0D Overture.skc"
Copy /y /b "0E\Out\0E This Horizon.bin" "Preview\Data\Knuckles Maniax\0E This Horizon.skc"
Copy /y /b "0F\Out\0F Take Off.bin" "Preview\Data\Knuckles Maniax\0F Take Off.skc"
Copy /y /b "10\Out\10 Combination.bin" "Preview\Data\Knuckles Maniax\10 Combination.skc"
Copy /y /b "11\Out\11 Take A Nap.bin" "Preview\Data\Knuckles Maniax\11 Take A Nap.skc"
Copy /y /b "12\Out\12 Surging Power.bin" "Preview\Data\Knuckles Maniax\12 Surging Power.skc"
Copy /y /b "13\Out\13 Mechanical Dance.bin" "Preview\Data\Knuckles Maniax\13 Mechanical Dance.skc"
Copy /y /b "14\Out\14 Tube Panic.bin" "Preview\Data\Knuckles Maniax\14 Tube Panic.skc"
Copy /y /b "14\Out\14 Tube Panic [extra drums].bin" "Preview\Data\Knuckles Maniax\14 Tube Panic [extra drums].skc"
Copy /y /b "15\Out\15 Crystal Nightmare.bin" "Preview\Data\Knuckles Maniax\15 Crystal Nightmare.skc"
Copy /y /b "16\Out\16 Childs Song.bin" "Preview\Data\Knuckles Maniax\16 Childs Song.skc"
Copy /y /b "17\Out\17 Soda Pop.bin" "Preview\Data\Knuckles Maniax\17 Soda Pop.skc"
Copy /y /b "18\Out\18 Pendulum.bin" "Preview\Data\Knuckles Maniax\18 Pendulum.skc"
Copy /y /b "19\Out\19 Silver Screen.bin" "Preview\Data\Knuckles Maniax\19 Silver Screen.skc"
Copy /y /b "1A\Out\1A Tachy Touch.bin" "Preview\Data\Knuckles Maniax\1A Tachy Touch.skc"
Copy /y /b "1B\Out\1B Chaotic World.bin" "Preview\Data\Knuckles Maniax\1B Chaotic World.skc"
Copy /y /b "1C\Out\1C Surprise.bin" "Preview\Data\Knuckles Maniax\1C Surprise.skc"
Copy /y /b "1D\Out\1D Nice Meeting You.bin" "Preview\Data\Knuckles Maniax\1D Nice Meeting You.skc"
Copy /y /b "1E\Out\1E Have A Happy Day.bin" "Preview\Data\Knuckles Maniax\1E Have A Happy Day.skc"
Copy /y /b "1F\Out\1F Reach The Goal.bin" "Preview\Data\Knuckles Maniax\1F Reach The Goal.skc"
Copy /y /b "20\Out\20 High Five.bin" "Preview\Data\Knuckles Maniax\20 High Five.skc"
Copy /y /b "21\Out\21 Decision.bin" "Preview\Data\Knuckles Maniax\21 Decision.skc"
Copy /y /b "22\Out\22 From Party To Party.bin" "Preview\Data\Knuckles Maniax\22 From Party To Party.skc"
Copy /y /b "23\Out\23 Have Some Fun.bin" "Preview\Data\Knuckles Maniax\23 Have Some Fun.skc"
Copy /y /b "24\Out\24 Oriental Legend.bin" "Preview\Data\Knuckles Maniax\24 Oriental Legend.skc"
Copy /y /b "25\Out\25 Steel Heart.bin" "Preview\Data\Knuckles Maniax\25 Steel Heart.skc"
Copy /y /b "26\Out\26 Tribute.bin" "Preview\Data\Knuckles Maniax\26 Tribute.skc"
Copy /y /b "27\Out\27 Destructive Power.bin" "Preview\Data\Knuckles Maniax\27 Destructive Power.skc"
Copy /y /b "28\Out\28 Just Another Day.bin" "Preview\Data\Knuckles Maniax\28 Just Another Day.skc"
Copy /y /b "29\Out\29 Decision 2nd.bin" "Preview\Data\Knuckles Maniax\29 Decision 2nd.skc"
Pause