cd /D "%~dp0"
KENSSharp.exe -r e "0_4MN.bin"
KENSSharp.exe -r e "0_5MN.bin"
KENSSharp.exe -r e "0_13MN.bin"
KENSSharp.exe -r e "0_Boss.bin"
KENSSharp.exe -r e "1_3MN.bin"
KENSSharp.exe -r e "1_5MN.bin"
KENSSharp.exe -r e "2_15MN.bin"
KENSSharp.exe -r e "3_12MN.bin"
KENSSharp.exe -r e "3_34MN.bin"
KENSSharp.exe -r e "3_5MN.bin"