cd /D "%~dp0"
KENSSharp.exe -r e "0_15MN.bin"
KENSSharp.exe -r e "0_Boss.bin"
KENSSharp.exe -r e "1_1MN.bin"
KENSSharp.exe -r e "1_2MN.bin"
KENSSharp.exe -r e "1_3MN.bin"
KENSSharp.exe -r e "1_4MN.bin"
KENSSharp.exe -r e "1_5MN.bin"
KENSSharp.exe -r e "2_13MN.bin"
KENSSharp.exe -r e "2_45MN.bin"
KENSSharp.exe -r e "3_5MN.bin"
KENSSharp.exe -r e "3_12MN.bin"
KENSSharp.exe -r e "3_34MN.bin"